shotgunsoftware/tk-core

- python/tank_vendor/shotgun_authentication/shotgun_authenticator.py
- python/tank_vendor/shotgun_authentication/user_impl.py
This is for backwards compatibility with pipelines and studios still using Python 2.6, as we do in some applications/environments.
See: https://docs.python.org/2/library/logging.html#logging.Logger.getChild (introduced in Python 2.7)
> Avoid use of a logging method introduced in Python 2.7 (2.6 compatibility)

- python/tank_vendor/shotgun_authentication/user.py
- python/tank_vendor/shotgun_authentication/user_impl.py
Desktop prints the current user for debugging, but because the ShotgunUser now proxies the implementation we can't know what type of user we actually have based on the class information. This will provide useful information about the user.
> Adding ShotgunUser.__repr__ for easier debugging.

- python/tank/util/shotgun.py
- tests/util_tests/test_shotgun.py
- Implements an app store specific proxy setting.
- Adds unit tests for both the original and new authentication logic
> For #34444, app store specific proxy

- python/tank_vendor/shotgun_deploy/constants.py
- python/tank_vendor/shotgun_deploy/errors.py
- python/tank_vendor/shotgun_deploy/io_descriptor/appstore.py
When launched, SG Desktop attempts to connect to the Toolkit app store to check for updates to the desktop startup framework. For studios that have blocked internet access, connections to the Toolkit app store are usually rejected, which is handled correctly and the startup process will continue normally and will emit a log message stating the app store was unreachable.
However, if the firewall is configured to drop the connection rather than reject it, the client is left waiting for a response. In this case the "client" is the Shotgun API handle that Toolkit uses, which by default specifies no explicit connection timeout value. This means the timeout used by the API falls back on the default value set by the specific socket implementation for your platform. This could mean the connection …
> for #35774: Sets a default timeout for the Toolkit app store connection

- python/tank/util/shotgun.py
Because the way the app store logic has been refactored in 0.18, changes needed to be manually merged from 0.17. This backs out of some logic which was specifically added solely for the purpose to be able to set the app store connection timeout. For the merge from 0.17 to 0.18, we did some adjustments in 5554d12 to make the app store timeout changes became 0.18 compatible, but we never removed the code which was added in 0.17, which is no longer used anywhere.
This logic was added so that technically a timeout parameter could be added to the normal shotgun connection as well as the app store connection, however this would only work if the shotgun connection 
was using script based credentials. I don't believe this is currently documented and adds complexity in what is essentially a legacy …
> Removes app store timeout logic

- python/tank/authentication/session_cache.py
The desktop assumes that if you have authenticated on the site level, you are also authenticated on the project level. In 0.18, a new set of root paths (pending our discussion) are introduced and this means that there was a situation where auth info was stored on disk and readable for a 17 core but not for an 18 core. So if your project was 0.18 and your site config was 0.17, things wouldn't work.
This PR adds a fallback so that if the 0.18 config isn't found, it checks for the 0.17 one as well (similar to how the cache hook works). If none of them is found, the 0.18 path is returned.
> Authentication compatibility fallback

- python/tank/pipelineconfig.py
- python/tank/util/shotgun.py
In 0.17, the shotgun connection was happening on demand inside the descriptor code. In 0.18, a descriptor object is initialized with a shotgun connection. This is in order to provide better encapsulation, be able to better control where a shotgun connection stems from and ultimately run the descriptor API in an environment that doesn't necessarily require a full toolkit setup.
Unfortunately, We have a very special case where this is causing issues - when menu items are cached by the tank command and shotgun engine, this is taking place in an unauthenticated fashion - this is to prevent authentication prompts to pop up as part of a page load in Shotgun. This is very much a legacy case and something we will ultimately move away from when we release the next iteration on websockets based …
> #36806 descriptors for unauthenticated pathways

- python/tank/bootstrap/manager.py
- python/tank/bootstrap/resolver.py
- python/tank/descriptor/io_descriptor/factory.py
- python/tank/util/local_file_storage.py
This implements the final round of 0.18 interface changes.
- Added `do_shotgun_config_lookup` property (defaults to `True`) which makes i possible for "static" plugins such as RV to implement a fixed policy where shotgun is not interrogated for config overrides.
- Removed `resolve_latest_base_configuration` property - this is in anticipation of a future introduction of a descriptor update policy which will allow us to control updates in a generic and much more flexible manner. The initial version of 0.18 bootstrap will always resolve the latest of whatever descriptor is provided. For static distributions, manual descriptors are normally used and these do not implement a concept of latest version, making this change of policy safe for such implementations.
- Added `entry_point` property - …
> #36862 #36866 Final round of 0.18 interface changes

- hooks/cache_location.py
- python/tank/bootstrap/configuration.py
- python/tank/bootstrap/constants.py
- python/tank/bootstrap/resolver.py
- python/tank/path_cache.py
- python/tank/pipelineconfig.py
- python/tank/platform/bundle.py
- python/tank/util/local_file_storage.py
This is a subtle yet important change to allow for a fully sandboxed and consistent setup when running TaaP entry point name spaces.
Previously, we only distinguished between toolkit configs that either had a pipeline config id or not. Most TaaP setups will not have a pc id in shotgun and this change ensures that a TaaP setup cache structure works the same way as cache structures for toolkit configs that have a pipeline config id. 
This is an example of the cache structure with this change:
Note the `site.rv_review` entry that is a config that is bootstrapped out of TaaP and doesn't have a pipeline config id in shotgun - this is now positioned alongside traditional configs that have ids. We don't have an id, so instead the entry point is used to create a cache "sandbox".
Further changes: …
> #36909 entry point support for local cache manager

- python/tank/util/shotgun.py
On Shotgun versions where supported, register publish now explicitly sets the storage it wants to associate with a published file. If not supported or if the storage is not found in Shotgun, it gracefully falls back on the previous implementation, e.g. passing the entire path to Shotgun and relying on Shotgun to compute which storage to associate with. Also added debug logging around the publish process.
> #30005 Support for Shotgun specific storage syntax

- python/tank/commands/migrate_entities.py
Tank updates internal interface was updated but the migrate publish command was 
never updated. This happened a *very* long time ago. Now works again.
> #37162 [minor] Fixes broken call to tank updates

- python/tank/log.py
Turns out you need at least one backup file in order for the rotating log file handler
in python to actually be able to rotate the files. We had this set to zero, effectively forcing
the rotation never to happen, causing the file size to grow indefinitely.
This adds a single backup, allowing the files to rotate.
> #37214 Fixed issue with limit for log files

- python/tank/descriptor/io_descriptor/appstore.py
- python/tank/descriptor/io_descriptor/base.py
- python/tank/descriptor/io_descriptor/git_branch.py
- python/tank/descriptor/io_descriptor/git_tag.py
- python/tank/descriptor/io_descriptor/shotgun_entity.py
- python/tank/util/__init__.py
- python/tank/util/errors.py
- python/tank/util/shotgun.py
Adds smarter retries when a bad attachment is downloaded. This helps with the particularly annoying issue where desktop says "file is not a zip file". Instead, toolkit will now retry 4 times (which likely will resolve the issue) and if that still fails, it will emit the following error message:
```
Failed to download sgtk:descriptor:app_store?version=v0.7.37&name=tk-multi-workfiles2 
from the Toolkit App Store (https://tank.shotgunstudio.com)
```
> #37216 Better retry when attachment downloads fail

- docs/utils.rst
- python/tank/commands/core_localize.py
- python/tank/descriptor/io_descriptor/appstore.py
- python/tank/descriptor/io_descriptor/git_tag.py
- python/tank/descriptor/io_descriptor/manual.py
- python/tank/util/filesystem.py
Fixed a bug which was causing certain items to be missing from a new project's app cache when it the project was created from another project's config. This issue was caused by the fact that toolkit maintains a global in-memory cache of descriptors. The assumption is that if a descriptor points at Core 1.2.3, this descriptor can be used by any process that wants to pick up v1.2.3 (see [here](https://github.com/shotgunsoftware/tk-core/blob/3813ea760484c4b418d468120032ab9a1f919b81/python/tank/descriptor/io_descriptor/factory.py#L79)).
Special logic was used inside the localize method to determine if an item should be copied or not - making assumptions about how descriptors were implemented under the hood. These assumptions not only conflict with this global cache, but generally going …
> #37386 Fixed issue preventing project copy in Shotgun desktop

- python/tank/commands/core_localize.py
- python/tank/descriptor/descriptor.py
- python/tank/descriptor/io_descriptor/appstore.py
- python/tank/descriptor/io_descriptor/base.py
- python/tank/descriptor/io_descriptor/git_branch.py
- python/tank/descriptor/io_descriptor/git_tag.py
- python/tank/descriptor/io_descriptor/manual.py
- python/tank/descriptor/io_descriptor/path.py
- python/tank/descriptor/io_descriptor/shotgun_entity.py
- python/tank/util/filesystem.py
See #306 for initial attempt to fix this issue. This is a more elegant, less brute force approach to fixing localize bug happening when you try to set up a new project based on an existing project.
This implementation is smarter and has the same performance characteristics as the 0.17 version.
Introduces `descriptor.clone_cache(target_bundle_cache_root)` method which is generally useful for any time of bundle cache management (likely to be useful soon in TaaP).
- As a consequence, reshuffled descriptor code which removes some duplication
- As a side effect, this will fix a long standing issue with manual and git descriptors not being copied across from existing projects (YAY!)
> #37386 Improved version of PR #306

- python/tank/hook.py
- python/tank/util/loader.py
The hook interface is a boundary where toolkit executes user code. With 0.18 and its improved logging, we can ensure to consistently trap any errors passing through this boundary.
This change adds a low level exception logging trap for all hooks in toolkit, ensuring that whenever a hook fails to load or execute, this is logged to the logger (and the log file):
```
2016-07-15 09:43:48,642 [90897 ERROR sgtk.core.hook] Exception raised while executing hook '/mnt/wintermute/configs/18_mac/install/core/hooks/tank_init.py'
File "/mnt/wintermute/configs/18_mac/install/core/python/tank/hook.py", line 506, in execute_hook_method
ret_val = hook_method(**kwargs)
File "/mnt/wintermute/configs/18_mac/install/core/hooks/tank_init.py", line 25, in execute
a = b + c …
```
> #37459 Adds exception logging to hooks

- scripts/tank_cmd.py
Fixes a long standing issue where the `tank` command wasn't working in Python 2.5
> #37555 fixes issues with the tank command and python 2.5

- python/tank/commands/setup_project_params.py
Fixes a regression where projects set up from a git based config was picking up the tag with the highest version number rather than the latest commit from master (as it was previously).
> #37486 Setup project from git regression

- python/tank/__init__.py
- python/tank/bootstrap/manager.py
- python/tank/bootstrap/resolver.py
- python/tank/commands/core_upgrade.py
- python/tank/descriptor/descriptor.py
- python/tank/descriptor/io_descriptor/manual.py
- python/tank/pipelineconfig.py
- python/tank/platform/environment.py
- python/tank/platform/environment_includes.py
- python/tank/util/filesystem.py
- python/tank/util/shotgun.py
- scripts/build_plugin.py
- tests/commands_tests/test_updates.py
- tests/platform_tests/test_validation.py
This adds a new script to toolkit, located here: `scripts/build_plugin.py`. This script introduces guidelines and process around plugin development (Docs TBD) 
```
> python build_plugin.py -h
Usage: build_plugin.py source_path target_path (run with --help for more information)
Builds a standard toolkit plugin structure ready for testing and deploy
Options:
-h, --help   show this help message and exit
-d, --debug  Enable debug logging
Examples:
> python build_plugin.py ~/dev/tk-maya/plugins/basic /tmp/maya-plugin
```
See screencast video for an introduction.
Other changes:
- Adds a `__version__` to core. 😋 
- Descriptor primary and fallback paths now support environment variables and tildes
- The bootstrap logic has been changes so that if a `base_configuration` descriptor is passed in …
> #37434 Plugin build script

- python/tank/bootstrap/manager.py
- python/tank/bootstrap/resolver.py
This adds Shotgun runtime configuration lookup to the Toolkit boostrap manager.
This means that it's possible to implement dynamic overrides via the existing Pipeline Configuration concept in Shotgun, allowing for shotgun users to take control over the behaviour, configuration and deployment of plugin based payloads. Notable points:
- The system will look for the fields `entry_point` or `sg_entry_point` to determine the entry point. The latter field is to ensure backwards compatibility with older shotgun versions, where you can create this field by hand.
- The lookup will first check the traditional path fields, then look for the fields `descriptor` and `sg_descriptor` where it expects to find a descriptor uri string to resolve the config from
- The ToolkitManager.pipeline_configuration …
> #36869 Shotgun Pipeline Configuration Lookup

- scripts/build_plugin.py
**Generate 'get_sgtk_pythonpath()' in 'manifest.py' rather than 'add_sgtk_to_pythonpath()'.**
The extraction of the core path relative parts is now more robust whatever the base location of the 'bundle_cache' (Shotgun cache root vs. plugin root).
Generate helper function 'get_sgtk_pythonpath()' that:
- Calls 'os.path.join()' with separate core path parts to make sure the right separator is used.
- Does NOT insert the path in 'sys.path' to let the caller add it to the pythonpath as it pleases.
Usage example:
tkcore_python_path = manifest.get_sgtk_pythonpath(PLUGIN_ROOT_PATH)
if tkcore_python_path not in sys.path:
sys.path.insert(0, tkcore_python_path)
> #37046: Update 'build_plugin.py'.

- python/tank/descriptor/io_descriptor/git.py
- python/tank/util/filesystem.py
- tests/descriptor_tests/test_git.py
Fixes a regression where projects set up with a git based config didn't end up with a `.git` folder. 
This was an oversight when trying to improve the behaviour of the `copy_folder` generic I/O command. The `descriptor.copy()` command has been updated to always include `.git` folders when a git descriptor (tag or branch) is copied across. Also fixes an issue with how the skip list is handled within the `copy_folder()` method.
> #38064 .git not copied across at project setup (and in other places)

- developer/build_plugin.py
- docs/bootstrap.rst
- hooks/cache_location.py
- python/tank/bootstrap/baked_configuration.py
- python/tank/bootstrap/cached_configuration.py
- python/tank/bootstrap/configuration_writer.py
- python/tank/bootstrap/constants.py
- python/tank/bootstrap/manager.py
- python/tank/bootstrap/resolver.py
- python/tank/log.py
- python/tank/path_cache.py
- python/tank/pipelineconfig.py
- python/tank/platform/bundle.py
- python/tank/util/local_file_storage.py
- scripts/tank_cmd.py
- tests/bootstrap_tests/test_resolver.py
- tests/util_tests/test_local_path.py
This renames `entry_point` to `plugin_id` across the code. Existing plugins are likely (but not guaranteed) to be backwards compatible.
Also implements site level overrides for pipeline configurations. Practically, this means that if you are user john smith and you start up the following:
```
mgr = sgtk.bootstrap.ToolkitManager()
mgr.base_configuration = "sgtk:descriptor:app_store?name=tk-config-default"
mgr.plugin_id = "test.maya"
mgr.bootstrap_engine("tk-maya", entity={"type": "Project", "id": 123})
```
The following resolution order will be attempted:
1. First toolkit will check for a project level, user associated pipeline configuration with
- `PipelineConfig.users` field containing john smith
- `PipelineConfig.project` field set to project 123
- `PipelineConfig.plugin_id` matching …
> #38304 #37933 entry point > plugin id, site level overrides

- python/tank/path_cache.py
- tests/core_tests/test_path_cache.py
- tests/python/tank_test/tank_test_base.py
When the incremental sync runs, toolkit will determine what to update via the data in the database, then pull down the updates from shotgun and lastly update the database.
There is no acidity or transactions around this because of the Shotgun API, so there is a possibility that two syncs run in parallel and both end up deciding that they should insert a row in the db representing a new object that exists in shotgun but not yet in the db.
This used to result in errors due to the unique db constraint:
```
sqlite3.IntegrityError: columns entity_type, entity_id, root, path, primary_entity are not unique
```
This fix fixes that issue by gracefully falling back on the sql level by doing a `INSERT OR IGNORE INTO`, meaning if the record exists, it is skipped.
Also added several concurrency tests …
> #34448 improved sqlite uniqueness checks

- python/tank/platform/__init__.py
- python/tank/platform/constants.py
- python/tank/platform/util.py
This provides a standard html string for use when displaying hyperlinks in QLabels.
> #38369: Adds get_hyperlink_html utility function to sgtk.platform.

- python/tank/templatekey.py
- tests/core_tests/test_templatekey.py
Adds two new properties to string keys:
More examples:
`templates.yml`
``` yaml
keys:
initial:
type: str
subset: '([A-Z])[a-z]* ([A-Z])[a-z]*'
subset_format: '{1}{0}'
strings:
simple_test: "before_{initial}_after"
```
Code:
``` python
>>> tk.templates["simple_test"].apply_fields({"initial":"Manne Ohrstrom"})
'before_OM_after'
>>> tk.templates["simple_test"].keys["initial"].subset
'([A-Z])[a-z]* ([A-Z])[a-z]*'
>>> tk.templates["simple_test"].keys["initial"].subset_format
'{1}{0}'
>>> tk.templates["simple_test"].get_fields("before_OM_after")
{'initial': 'OM'}
>>> tk.templates["simple_test"].apply_fields({"initial":"Manne"})
File "<console>", line 1, in <module>
File "/mnt/wintermute/the_evil_mimes/install/core/python/tank/template.py", line 243, in …
```
> #37767 Support for substring template keys

- python/tank/api.py
- python/tank/pipelineconfig.py
- python/tank/platform/application.py
- python/tank/platform/engine.py
- python/tank/platform/framework.py
- python/tank/util/metrics.py
A more generic approach to providing a way to log a metric once per session. 
Adds a `log_once` boolean argument to all metric logging methods. The metrics queue now uses `repr` to identify metrics and keeps track of which metrics have been previously logged. When `log_once` is supplied as `True`, the metric will not be added to the queue if another metric with the same identifier was previously logged. 
Replaces PR #354.
> #39255 Only log metrics for custom core hooks once per session

- python/tank/platform/qt/busy_dialog.ui
- python/tank/platform/qt/ui_busy_dialog.py
This change simply makes the busy dialog slightly larger. This seemed
preferable to making the font size smaller or trying to do anything dynamic.
I searched through all existing calls to this in our repos, and the given
case seems to be the longest message displayed. This will give us a little more
room to work with and we can do something a little smarter in the future if
need be.
Previous size:
New size:
>  #38647 Fixes issue where busy dialog text is cut off

- python/tank/platform/engine.py
Engines without Qt available, like tk-shell and tk-shotgun, will crash with the new font code. I've added a check for has_ui.
> For 38647, fix for engines that don't have Qt available.

- python/tank/platform/engine.py
- tests/platform_tests/test_engine.py
Previously, we were recaching app settings, but we were NOT doing so for engine settings. That's a bug, and this resolves it.
> #39632: Engine settings are recached during context change.

- python/tank/commands/console_utils.py
- python/tank/commands/update.py
- python/tank/platform/validation.py
- python/tank/util/version.py
- tests/fixtures/config/bundles/test_app/info.yml
- tests/fixtures/config/bundles/test_framework/framework.py
- tests/fixtures/config/bundles/test_framework/info.yml
- tests/fixtures/config/env/test.yml
- tests/fixtures/config/env/test_dump.yml
- tests/fixtures/config/env/test_post_update_new_parser.yml
- tests/fixtures/config/env/test_post_update_old_parser.yml
- tests/platform_tests/test_application.py
If a bundle requires a minimum version of a specific framework, that can be specified in its `info.yml`.
```
frameworks:
- {"name": "tk-framework-widget", "version": "v0.2.x", "minimum_version": "v0.2.3"}
```
When `tank updates` is run and a bundle is updated, an additional step is taken to ensure that any required frameworks are also updated to at least the `minimum_version` requirement specified in the bundle's `info.yml`. This update occurs automatically, and without user confirmation, to ensure that the newly-updated bundle will function properly.
> #30254: Adds a "minimum_version" setting to bundle framework requirements.

- python/tank/platform/qt/tankqdialog.py
When there is no file system locations, hide `TankQDialog` _Jump to File System_ and _Jump to Shotgun_ buttons.
See the attached images with and without the buttons.
> #39476: When there is no file system locations, hide some Jump buttons.

- tests/python/tank_test/tank_test_base.py
If the pipeline config is not updated, the TestCase will still use the pipeline_config created in setUp() and so may fail with 'ShotgunError: TankType is not a valid entity' as the default config does not define "published_file_entity_type": "PublishedFile".
> reload the pipeline config when applying fixtures 

- python/tank/platform/engine.py
This change simply ensures `clear_busy()` is called if the user clicks the busy dialog while visible. Previously this didn't occur and the engine held a reference to a window that wrapped a closed busy dialog. This prevented the busy dialog from being shown again.
> #40003 Bug fix for global busy dialog

- python/tank/__init__.py
- python/tank/platform/environment.py
- python/tank/util/yaml_patcher.py
- tests/fixtures/config/bundles/test_app/info.yml
- tests/platform_tests/test_application.py
- tests/platform_tests/test_environment.py
Use utf-8 encoding when creating Python str objects from yaml unicode to allow for the storage of non-ascii characters in environment configuration and bundle manifest yaml files. This overrides the default behavior of the yaml and ruamel_yaml modules, which use 'ascii' encoding instead.  Handle ImportError exceptions from older versions of tk-framework-desktopstartup (<= v1.3.20) that do not have the ruamel_yaml module installed.
> 39348 Use utf-8 encoding when parsing strings from yaml

- python/tank/bootstrap/manager.py
Add property `ToolkitManager.caching_policy` to specify the config caching policy to use when bootstrapping.
- Setting it to `ToolkitManager.CACHE_SPARSE` will make the manager download and cache the sole config dependencies needed to run the engine being started. This is the default caching policy.
- Setting it to `ToolkitManager.CACHE_FULL` will make the manager download and cache all the config dependencies.
> #40101: Add a caching policy parameter to bootstrap.

- python/tank/util/shotgun.py
- tests/util_tests/test_shotgun.py
Register publish now quotes urls, as required by the sg server.
Note: this solution does not transform already transformed strings, so should be safe to deploy even to scenarios where this bug has been worked around outside of core, e.g.
```python 
>>> path = "foo bar"
>>> urllib.quote(path, safe="%/:=&?~#+!$,;'@()*[]")
'foo%20bar'
>>> urllib.quote('foo%20bar', safe="%/:=&?~#+!$,;'@()*[]")
'foo%20bar'
```
> #40596 fixed bug with register publish not handling urls with spaces

- python/tank/bootstrap/manager.py
Log a user activity metric when an engine is bootstrapped.
For example:
Module: `tk-bootstrap basic.maya` or `tk-bootstrap classic`
Action: `Launched engine tk-maya in project context`
Tracing what is being dispatched to the Shotgun API registration endpoint helped me make sure the tk-bootstarp log is properly put in the metric logging queue.
> #37533: Collect bootstrap metrics.

- python/tank/hook.py
- tests/core_tests/test_hook.py
This adds url support to `hook.get_publish_path()` and `hook.get_publish_paths()`. Practically speaking, this means that we can now publish items with a `file:///path` style url (rather than relying on local storage based paths) and then recall them via the loader later on.
> #40630 adds file url support to hook.get_publish_path()

- python/tank/api.py
- python/tank/errors.py
- python/tank/util/shotgun.py
- tests/util_tests/test_shotgun.py
If one of the paths listed as a possible dependency of a published file is malformed or doesn't conform to a single template, it is skipped. The previous behavior was an uncaught `TankError` that would errantly kill a publish.
> Skips problematic paths when finding dependent publishes.

- python/tank/path_cache.py
Step entities are a special case. When we encounter the need for a user to unregister_folders on a Step, they should be instructed to unregister the folder path directly rather than by entity.
> Corrects Step entity message when unregister_folders is required.

- python/tank/descriptor/io_descriptor/git_tag.py
This will choose taggerdate or committerdate for us, depending on tag type.
Quick test results show the sorting working:
```
>>> dd = sgtk.descriptor.io_descriptor.git_tag.IODescriptorGitTag(dict(type="git", path="https://github.com/shotgunsoftware/tk-multi-shotgunpanel.git", version="v1.2.7"), 0)
>>> dd
<IODescriptorGitTag sgtk:descriptor:git?path=https%3A//github.com/shotgunsoftware/tk-multi-shotgunpanel.git&version=v1.2.7>
>>> dd.get_latest_version()
<IODescriptorGitTag sgtk:descriptor:git?path=https%3A//github.com/shotgunsoftware/tk-multi-shotgunpanel.git&version=v1.3.1>
```
> Uses creatordate when sorting version tags of a git repo.

- python/tank/descriptor/io_descriptor/base.py
Determines existence of a bundle based on directory existence instead of looking for info.yml.
> Fix for bundle existence check in the descriptor API.

- python/tank/bootstrap/constants.py
- python/tank/bootstrap/manager.py
- python/tank/platform/engine.py
- python/tank/platform/software_launcher.py
- tests/fixtures/config/bundles/test_engine/startup.py
- tests/platform_tests/test_software_launcher.py
- Drops the options `display_name` and `icon` from the `SoftwareLauncher.scan_software()` method. After building maya, photoshop and houdini, it seems better to drop these. It doesn't make sense that each engine is responsible for implementing the logic defining how name and icon overrides should happen. Separation of concerns - this should take place in the launch app. The scan software method should only do what it says on the tin -- scan for the given DCC and return a list of matches.
- Added `SoftwareLauncher.get_standard_plugin_environment()` that computes and returns the following env variables:
- `SHOTGUN_SITE`: The current shotgun site url
- `SHOTGUN_ENTITY_TYPE`: The current context
- `SHOTGUN_ENTITY_ID`: The current context
- `SHOTGUN_PIPELINE_CONFIGURATION_ID`: The current …
> #40780 SoftwareLauncher interface tweaks

- python/tank/platform/software_launcher.py
- tests/platform_tests/test_software_launcher.py
Adds the following methods to the `SoftwareLauncher` class:
> #40780 Adds minimum version tools to SoftwareLauncher

- python/tank/bootstrap/manager.py
- tests/bootstrap_tests/test_manager.py
Adds a helper method which extracts an entity from a std environment:
> #40780 adds get_entity_from_environment method

- python/tank/hook.py
- tests/fixtures/config/hooks/more_hooks/config_test_hook.py
- tests/platform_tests/test_application.py
Fixes a bug (affecting the new publisher) which would only happen when you have complex inheritance chains for hooks. We now commonly apply the following sort of pattern:
```
some_hook: {self}/collector.py:{self}/maya.basic/collector.py
```
If the `disk_location` is called from within `{self}/collector.py`, we expect the path returned to be `{self}` and when we call it from within `{self}/maya.basic/collector.py`, we expect it to be `{self}/maya.basic`. This was not previously the case - in the past, it would always return the path to the leaf class, e.g. in this case the path `{self}/maya.basic`.
This fix addresses this. In the case `disk_location` is called from outside a hook, we always return the disk location of `self`, eg. the location of the leaf hook in the inheritance.
> #41090 Fixes to hook.disk_location and inheritance

- docs/platform.rst
- python/tank/bootstrap/cached_configuration.py
- python/tank/commands/migrate_entities.py
- python/tank/platform/constants.py
- python/tank/util/shotgun.py
- tests/fixtures/config/bundles/test_app/info.yml
- tests/fixtures/config/env/test.yml
- tests/fixtures/config/env/test_post_update_new_parser.yml
- tests/fixtures/config/env/test_post_update_old_parser.yml
I noticed that we still refer to tank type in the documentation. Toolkit already supported a `publish_type` equivalent, this PR switches the docs over to use that term instead. Added simple unit tests. This is no attempt to update or extend the docs, it's just the minimal work to switch things across and stop mentioning tank.
> #40850 Tank Type -> Publish Type

- python/tank/util/shotgun.py
- tests/util_tests/test_shotgun.py
Fix to not consider `//something/foo/bar` paths as urls but as regular paths.
* Removed the test checking the `netloc` if the `scheme` is empty.
* Added some unit tests.
> 40401 register publish url bug

- python/tank/util/shotgun/publish_creation.py
- tests/util_tests/test_publish.py
This PR adds an optional `dry_run` flag to the `register_publish` method. This is to be used to get the publish data `dict` that would be used to create a published file entry in SG. The need for this arises from our inability to filter publishes by file via the SG api. We use this method to get the publish data `dict`, then run a `find()` filtering on everything else. And then the client code can compare the returned publishes with the path in question. So this is essentially a way to ensure the find filters match the data that would be used to create a published file entry. 
Originally approved on zc branch #433
> Adds dry_run option to register_publish

- python/tank/context.py
- tests/core_tests/test_context.py
- `str(ctx) now returns `"Project xxx"`. Previously, it just returned `"xxx"`.
- Added unit tests for string rep.
> [minor] Tweaks to project context string representation

- docs/descriptor.rst
- python/tank/descriptor/io_descriptor/appstore.py
- python/tank/descriptor/io_descriptor/base.py
- python/tank/descriptor/io_descriptor/git_tag.py
- python/tank/descriptor/io_descriptor/shotgun_entity.py
Adds support for an optional label parameter for app store descriptors:
```
import sgtk
mgr = sgtk.bootstrap.ToolkitManager()
mgr.base_configuration = "sgtk:descriptor:app_store?name=tk-config-default&label=v2018.2"
e = mgr.bootstrap_engine("tk-engine")
```
The bootstrap above code will look for `tk-config-default` labelled `v2018.2` and use the latest one. This allows for a workflow where a single stream of updates can target several different plugin releases. The primary use case for this is that you want a single config to drive plugin based integration. Each plugin pulls the DCC version and uses this as the label. So a plugin running in DCC 2018.1 will look for `name=tk-config-default&label=v2018.1`, DCC 2018.2 will look for `name=tk-config-default&label=v2018.2` etc. This allows for …
> #42005 App store descriptor label support.

- python/tank/bootstrap/resolver.py
- tests/bootstrap_tests/test_resolver.py
The resolver's default for plugin_id is None. If it's in that state then it shouldn't try go match against that None with fnmatch.
> For #41692: Doesn’t attempt to match plugin_ids if there isn’t one to match.

- python/tank/util/shotgun/publish_resolve.py
- tests/util_tests/test_load_publish.py
QA fixes for #41300 - handling of how storages are resolves when a publish is resolves into a path.
- Tweaks to sphinx docs with better examples and clearer docs.
- Added support for adding an os platform to a local storage at runtime via an env var so that you can augment a local storage that is missing an os platform at runtime. this brings symmetry to the operations you can perform across `file://` links and local storage publishes.
> #41300 storage followup

- python/tank/bootstrap/constants.py
- python/tank/bootstrap/manager.py
- python/tank/platform/engine.py
Fixes a subtle issue where you would get errors when bootstrapping into an older project using the latest desktop server. The latest core has updated its `start_engine` so that it correctly handles both modern and legacy cases, however if you have an older core for a project you won't have these changes and the `shotgun_xxx.yml` legacy env files will therefore not be considered.
This fix ensures that the bootstrap logic runs the old shotgun-specific engine startup logic for old cores to ensure that we pick up `shotgun_xxx.yml` envs exactly the way it's done in the `tank` command.
> #42750 fixes backwards compatibility for shotgun envs

- python/tank/bootstrap/manager.py
The check for is_version_older would return False in this case. The result was that the new logic would be used, even though we don't actually know if the target tk-core is new enough to handle it.
> For #43024: Handles an old core with a version of “HEAD” in its info.yml.

- python/tank/bootstrap/resolver.py
This then corrects an issue with accessing the config's roots data as stored in roots.yml. This bug only affected descriptors created for classic-style configs by way of the bootstrap api's config resolver class.
> For $43057: Corrects the path given to create_descriptor for path-type configs.

- tests/run_tests.py
Coverage report was incorrect, as we were importing `tank` before starting coverage reporting, which immediately reported zero coverage from any code that gets executed at import time. We went from 39% coverage to 54%!
To do this I've had to make coverage initialize much earlier since we set up logging before running the tests. Since I was moving so much code around, I decided I would split up the `main` into multiple methods for clarity.
> Fixed coverage report

- developer/build_bundle_cache.py
- developer/build_plugin.py
- docs/descriptor.rst
- python/tank/bootstrap/configuration_writer.py
- python/tank/bootstrap/resolver.py
- python/tank/commands/core_upgrade.py
- python/tank/descriptor/__init__.py
- python/tank/descriptor/descriptor.py
- python/tank/descriptor/io_descriptor/__init__.py
- python/tank/descriptor/io_descriptor/factory.py
- tests/bootstrap_tests/test_resolver.py
- tests/descriptor_tests/test_api.py
- tests/descriptor_tests/test_io_descriptors.py
When a pipeline configuration was overridden in Shotgun, it had to be an absolute reference to a version. Omitting the version number keyword didn't work. This PR changes that.
- It adds a new helper method to standardize this pattern:
- it updates several places where `"version"` is incorrectly hard coded and the logic is overly simplistic.
- it adds support for shotgun descriptors tracking latest
- it adds support for core definitions (in the config) which are tracking latest
> #43137 fixes issue with sg descriptor latest lookups

- python/tank/bootstrap/manager.py
- python/tank/platform/engine.py
This resolves an issue where the wrong entity type was passed to start_shotgun_engine when the legacy start was required for the shotgun engine.
This removes legacy compatibility logic from sgtk.platform.engine and puts that responsibility on the bootstrap manager instead. That approach also allows us to remove the core version check that was required in the previous implementation.
> For #43060: Refactors the legacy path for tk-shotgun bootstrapping.

- python/tank/bootstrap/manager.py
- python/tank/folder/configuration.py
- python/tank/pipelineconfig.py
- python/tank/pipelineconfig_utils.py
- python/tank/platform/environment.py
- python/tank/platform/environment_includes.py
- python/tank/util/shotgun/connection.py
- tests/platform_tests/test_engine.py
- tests/util_tests/test_yaml_cache.py
The yaml parser, and therefore the yaml cache, return None for empty yml files. We were about 50/50 on handling that case gracefully.
> For #43236: Handles empty yaml files gracefully.

- python/tank/platform/engine.py
Added fix for incorrectly updating the var self.__application_pool
It should now only update the pool with the app if the app's instance_name matches the instance name in the loop.
The result of which should mean that when you have more than one instance of an app configured on an engine, it will correctly show all app instances in the menu after changing context.
Before it was incorrectly updating the self.__application_pool, by looping over every app and adding it into the pool regardless of whether the apps path matched and the instance name matched
Before the fix it would look like this:
```
{'/sg_toolkit/greyhounddev.shotgunstudio.com/configs/life_of_a_slug/install/app_store/tk-multi-about/v0.2.5': {'tk-multi-about': <Sgtk App 0x147a88a90: tk-multi-about, engine: <Sgtk Engine …
```
> # 43403 Fix app reuse on context change

- python/tank/descriptor/io_descriptor/appstore.py
Adds better protection from a case when the downloads succeed but the writing of event log entries fail. This is an unusual case but has been encountered in the wild.
> [minor] Adds better error protection in app store download

- python/tank/commands/core_upgrade.py
The version of core the user is updating to is now clearer from the message printed out to the command line.
example of new message:
```
You are currently running version v0.18.93 of the Shotgun Pipeline Toolkit
Newer version v0.18.100 is available.
Change Summary:
The ToolkitManager can now be used to bootstrap into
projects using core v0.15.20.
Detailed Release Notes:
https://support.shotgunsoftware.com/hc/en-us/articles/219039838#v0.18.100
Please note that if this is a shared core used by more than one project, this
will affect the other projects as well.
Update to v0.18.100 of the Core API? [yn]
```
new and changed bits are
`Newer version v0.18.100 is available.`
and
`Update to v0.18.100 of the Core API? [yn]`
> #43927 Improved core update message

- python/tank/platform/engine.py
* Enabled by setting the `SGTK_QSS_FILE_WATCHER` env. variable to 1, which seems safer than basing it on the descriptor being a _dev_ descriptor.
* Repeated in a couple of docstrings that potential problems might happen if used in production.
* Use `Engine. _apply_external_stylesheet` to set the watcher, as it seems to be the piece of code which is used by all engines when creating dialogs or panel.
* Please note that watchers stay around once set, even after dialogs are closed. This is one of the reasons why the watcher should only be used when doing some dev work. They don't cause problems, but quite a few could pile up if used in production.
> 40852 style sheet watcher

- setup/root_binaries/tank.bat
We have functionality to expand environment variables in interpreter files on Mac/Linux but this was previously not ported to Windows. This adds that support so that users can specify an environment variable as part of their interpreter settings on Windows and it gets correctly picked up by the tank.bat command.
> for #34908: Expand env vars in interpreter files on Windows

- python/tank/commands/cache_apps.py
- python/tank/commands/update.py
- python/tank/commands/validate_config.py
In the situation where the loading of the environment failed it wouldn't log which environment it was on. The logging for the environment has been moved to before the loading of the environment.
> #44167 reorder validate logging

- python/tank/context.py
- tests/core_tests/test_context.py
When constructing context objects from the factory functions provided in `sgtk.context`, we want to know what the source entity was, even if it was transformed into some other context. This transformation occurs for some entity types; most notably PublishedFile entities, where we want to construct a context based on what the PublishedFile is linked to. Keeping track of the source PublishedFile entity allows us to provide an environment specific to that entity type from pick_environment.
I added tests!
> For #44082: Keeps track of the source entity as given to context factory functions.

- python/tank/descriptor/descriptor.py
- tests/platform_tests/test_application.py
- tests/platform_tests/test_engine.py
Currently, if no 'documentation_url' entry is present in an app's info.yml, clicking the 'Documentation' button in the app's information sidebar does not result in any action.
By having the 'documentation_url' property on the Descriptor default to [toolkit's user guide URL](https://support.shotgunsoftware.com/hc/en-us/articles/115000068574-User-Guide) (instead of `None`), the user will be directed to this webpage if no specific entry is made in info.yml.
> #43063 The documentation_url property now defaults to toolkit's user guide URL.

- python/tank/authentication/console_authentication.py
- python/tank/authentication/errors.py
We prevent console-based authentication/re-authentication.
Should the saved session still be valid, a console-based application will be able to run.
> For #43941: prevent authentication when in console mode

- python/tank/util/qt_importer.py
We have an issue where it is possible to deadlock Maya on import of QtWebEngineWidgets. To work around that issue, we allow an environment variable to disable the import of that submodule.
> For #44161: Maya 2018 Windows compatibility.

- python/tank/path_cache.py
- tests/core_tests/test_path_cache.py
if your sqlite `in` statements are too large, the query engine will fail:
```
```
This fix batches them up into smaller chunks to avoid this limitation.
> #44931 path cache deletions are now batched

- python/tank/path_cache.py
- tests/core_tests/test_path_cache.py
This implements two optimizations for path cache:
This removes inner loop scenarios when syncing and can drastically improve path cache sync performance in certain scenarios.
When secondary entities are used, an additional check was carried out to ensure that a path wasn't already registered in the db. This was done in a non-optimal way, meaning that as the number of records grew in the db (especially for step), syncning could blow up in to a hidden `o(n^2)` complexity type scenario, causing millions of operations to be carried out.
This kills the complexity and issues a single query to the db for every record tested.
Find queries are batched into smaller chunks in order to help the shotgun backend db.
> #44807 Path cache optimizations

- python/tank/platform/environment.py
- python/tank/platform/environment_includes.py
- tests/fixtures/config/env/engine_location.yml
- tests/fixtures/config/env/test.yml
- tests/fixtures/config/env/test_post_update_new_parser.yml
- tests/fixtures/config/env/test_post_update_old_parser.yml
- tests/platform_tests/test_environment.py
The structure of the basic and default2 configs has highlighted some limitations of the `tank updates` command and how it deals with includes. In situations where multiple levels of references are used, we see the update logic replacing includes with baked-out data. This does not break the config, but it does destroy its include structure.
This attempts to do everything properly and in a backwards compatible way. There is a fair amount of inflexibility in the environment API that means this is pretty challenging. It's likely that this code is difficult to follow, but I would argue that it was before, as well, and only a significant refactor would correct that.
> For #44135: Properly handles multi-tiered include structures in configs.

- tests/run_tests.py
When writing tests from repos outside of tk-core, we constantly need to follow this pattern of
```
test_python_path = os.path.abspath(os.path.join( os.path.dirname(__file__), "..", "python"))
sys.path.append(test_python_path)
from base_test import MyCustomTestBase
```
or edit the `PYTHONPATH` in a shell script before invoking the tests.
Since the pattern of having `tests/python` is becoming common, the testing framework will acknowledge the fact and automate the process of adding to the `PYTHONPATH`.
> Adds {test_root}/python to the PYTHONPATH when running tests.

- python/tank/platform/bundle.py
- tests/fixtures/config/bundles/test_app/info.yml
- tests/fixtures/config/core/hooks/template_setting_resolution.py
- tests/platform_tests/test_application.py
In bundle.py, we have logic for resolving template-type settings for bundles that can have a hook defined as their value. In this situation, the referenced core hook is called, which will then return the value for the setting.
During the major refactoring work that came about as part of the zero config project, one of the bundle instance methods was converted to be a static function. The regression occurs as a result of a lingering reference to "self" in the now-static function. The fix is to default to the current bundle, but offer the option of passing in a bundle object explicitly.
> For # 45071: Fixes reference to self in a static function.

- python/tank/path_cache.py
Path cache performance tweaks based on client feedback to better the handle the case when people have a large number (500k+) of path cache entries:
- This adds a new path cache index to improve lookups when deleting path cache records.
- Also cranks up the paging to 8k (see https://sqlite.org/pragma.html#pragma_page_size) in order to improve I/O when there is a large volume of queries to commit and the path cache is stored on networked storage.
> Path cache indices and page size tweaks

- docs/descriptor.rst
Updated the docs to include information about the SHOTGUN_BUNDLE_CACHE_PATH environment variable and downloadable descriptors.
> #44757: Updated descriptor docs

- python/tank/util/user_settings.py
Logs the http_proxy as provided by SystemSettings. We do this from the UserSettings init routine as a convenience, as it contains sanitization logic needed to safely log proxy information, and we're guaranteed to only log it once at the time the UserSettings are instantiated as a singleton.
> For #43140: Logs the system http proxy.

- python/tank/descriptor/constants.py
- python/tank/descriptor/io_descriptor/appstore.py
- tests/descriptor_tests/test_appstore.py
From manual testing and usage of a packet capture utility I was NOT able to confirm that no additional Internet connections is made other than connections to the main SG site. Once I filtered out the obvious, what remained was at least connections to 2-3 remote machines. Although, usage of the new environment variable did prevent some connection to SG app store, I would still see some connections to some AWS machine which, I believe, relates to SG App Store.
I've tried setting up my own local SG server, I could then disconnect network adapters entirely but  whether or not I was using the new environment variable did not changed anything (beside maybe a few log file messages ) I suspected that my local installation of SG was not 100% complete and was missing at least some setup relating to …
> 44140 add toolkit ability to prevent internet connection

- python/tank/log.py
- python/tank/platform/constants.py
- python/tank/platform/engine.py
- tests/core_tests/test_log.py
* The intent is to ensure that any subprocesses spawned that make use of SGTK will inherit the global debug logging setting from the current process. A concrete use case is in tk-desktop, where we want toggling of the global debug state to cause any DCC launches to start with the same debug logging state.
* The tk-desktop engine no longer receives a debug toggle engine command. The engine itself provides this toggling capability from its advanced menu provided by desktop_window.py.
> For #43813: Toggling the global debug state sets TK_DEBUG in the environment.

- python/tank/platform/engine.py
Adds stubs for the following methods:
* get_session_path() - (Not implemented) Method that returns the path associated with the current session.
* get_session_dependencies() - (Not implemented) Method that returns the file path dependencies of the file.
Linked with: https://github.com/shotgunsoftware/tk-maya/pull/60
> SPLAT-83: Stubs for get_session_path() and get_session_dependencies()

- python/tank/api.py
Publisher slowness was due to using "name" instead of "content" as the field
required to prevent additional SG query when calling
`context_from_entity_dictionary`.
> #43803 Minor doc tweak to correct field name for Task

- python/tank/authentication/login_dialog.py
- python/tank/authentication/resources/login_dialog.ui
- python/tank/authentication/ui/login_dialog.py
- Removed the 'Use Single Sign-On (SSO)'/ 'Use Shotgun Account' link, that would toggle the login dialog GUI,
- Instead added auto-detection of SSO support (or not) to update the GUI accordingly,
- A QTimer is used to do a SSO support check on the URL only after the user is done typing,
- The dialog height has been reduced back to its original pre-SSO-support size
> For #44568: refactor the login dialog to automatically detect a SSO site

- tests/bootstrap_tests/test_backups.py
- tests/python/tank_test/tank_test_base.py
- tests/run_tests.py
Alternate & simpler solution to previously submitted PR: https://github.com/shotgunsoftware/tk-core/pull/550
The solution is just about wrapping everything the tests are creating into another temporary directory level that can be easily deleted afterwards.
Point to discuss:
- Whether or not to actually include work from the original PR
- Current default is NOT to clean anything unless the --clean-temp-data switch is used.
- What should be the value to the 'action' parameter (see below)?
Also, to address concerns by JF, I'm attaching a crude summary of running multiple test runs on OSX. The summary simply shows that cleaning up files only takes a tiny bit more time, about 0.42% more. I expect that results on Windows would be larger but still small. …
> For 43890: Fix unittest leaking fairly large amount of data

- python/tank/platform/software_launcher.py
We have an issue with `tk-maya` when creating `SoftwareLauncher` instances if there is no filesystem structure on disk for the context. The engine's `template_project` setting will not validate preventing the launcher from being created. 
This is a blunt solution that removes settings validation from the SW launcher. I will try to come up with a cleaner solution before end of day today. I'm out the rest of the week, so this is really just to get in front of @manneohrstrom for review. @mathurf will coordinate from here out. If this is good, it can be merged and tested. If not, we should discuss with @robblau how this affects defcon2 release.
> #45817 Removes settings validation from `SoftwareLauncher`

- python/tank/authentication/login_dialog.py
- python/tank/authentication/shotgun_shared/__init__.py
- python/tank/authentication/shotgun_shared/saml2_sso.py
- python/tank/authentication/user.py
This commit addresses the following points:
- Properly handles a missing Qt module (e.g. we allow regular Qt login with Username/Password),
- Isolate shotgun_shared module so that Qt modules are passed as arguments,
- Remove dependency of shotgun_shared on Toolkit components (Qt libraries and Logger),
- Connected the shotgun_shared logger to the Toolkit logger.
- Cleaned up the log messages, made them a bit more palatable to human readers,
- Removed commented out code,
> For 45519: cleanup SSO module.

- python/tank/authentication/shotgun_shared/saml2_sso.py
Support for NTLM authentication in Qt (which is usually handled automatically by modern browsers) must be handled via the authenticationRequired event on a web page's network access manager.
The code is simple, but is essential for NTLM support. Otherwise is is a no-op (if SSO is not used, NTLM is not used or on non-windows machines)
> Support for NTLM authentication on Windows machines

- hooks/cache_location.py
- python/tank/platform/bundle.py
- python/tank/util/local_file_storage.py
- tests/platform_tests/test_application.py
The goal of this work is to allow to cache data at the site level, rather than duplicating data per project / pipeline config / plugin id. Typical use of site caching would be thumbnails or SG queries issued from tk-framework-shotgunutils.
- Added `Bundle.site_cache_location` which allows to retrieve a cache location with just a `site` folder.
- Added unit tests for `cache_location` (project based) and `site_cache_location`.
- Mentioned in `CacheLocation.get_bundle_data_cache_path` that component params can be set to `None` to omit them.
- Changed internal comment to mention that not having a pc id nor a plugin id is a valid use case for site caches.
> For #43294, site level caching.

- python/tank/util/metrics.py
- tests/util_tests/test_metrics.py
This pull request is about adding very basic platform information to emitted metrics. To simplying Amplitude query I was asked to limit version string to minimum. Here are a few sample outputs:
{'OS Version': 'Debian 7', 'OS': 'Linux'}
{'OS Version': 'Ubuntu 12', 'OS': 'Linux'}
{'OS Version': '10.7', 'OS': 'Mac'}
{'OS Version': '10.13', 'OS': 'Mac'}
{'OS Version': '2000', 'OS': 'Windows'}
{'OS Version': 'XP', 'OS': 'Windows'}
{'OS Version': '7', 'OS': 'Windows'}
{'OS Version': '8', 'OS': 'Windows'}
{'OS Version': '10', 'OS': 'Windows'}
> 45379 update metrics api to track os info

- python/tank/descriptor/errors.py
- python/tank/descriptor/io_descriptor/downloadable.py
- python/tank/descriptor/io_descriptor/git.py
- python/tank/util/filesystem.py
- tests/descriptor_tests/test_downloadables.py
- tests/run_tests.py
This adds a fallback to the transaction system handling downloadble descriptor types.
Previously, the code would be downloaded into a temp space in the bundle cache, then upon completion the tmp folder would be renamed into its right bundle cache location. This is an atomic operation meaning its fast and transactional in nature, avoiding any potential file leftovers inside the bundle cache on failure.
In the wild, we have seen bugs on windows where this approach fails - possibly due to file locking because of AV scans kicking in after download - but we are not entirely sure yet.
This change implements a fallback, a plan B in case the rename fails. In this case, a slower and more elaborate process is initiated, whereby the temp content is copied into place and then the tmp space is cleaned …
> #45876 Safe copy fallback for bundle cache I/O transactions

- python/tank/bootstrap/errors.py
- python/tank/bootstrap/installed_configuration.py
- tests/bootstrap_tests/test_configuration.py
- tests/bootstrap_tests/test_resolver.py
Improves the error message you get in case you manually populate the `windows|mac|linux_path` fields on the pipeline configuration with a path, say to a configuration which was downloaded from github:
The error message and log warnings:
> #41067 [minor] Adds error check for installed configs.

- python/tank/commands/clone_configuration.py
- python/tank/commands/push_pc.py
- python/tank/commands/setup_project_params.py
- python/tank/descriptor/descriptor.py
- python/tank/descriptor/io_descriptor/factory.py
- python/tank/descriptor/io_descriptor/git.py
- tests/descriptor_tests/test_api.py
Tickets #36070 #37578 #39910 #40633 #43066 #44576
A collection of improvements related to git descriptors:
If you download a [zip](https://github.com/shotgunsoftware/tk-core/archive/master.zip) directly from github, this can be used by the advanced project setup:
(Note that this already works for the uploaded_config field in shotgun)
- The clone pipeline configuration method in shotgun (if you right click on a pc) now copies the `.git` folder as part of the cloning. This was not the case in recent versions of core, a regression introduced at some point in the 0.18 cycle.
- The push configuration tank command now also copies everything (including `.git` folders) when you perform the push
Previously, if your configuration was installed in a UNC path based location, git commands would not …
> Git improvements

- python/tank/hook.py
- python/tank/platform/bundle.py
- tests/platform_tests/test_application.py
This change adds a new, optional `base_class` argument to the `hook.create_hook_instance` method in core. This argument allows the calling code to override the hook base class used when loading the supplied hook paths. Having the ability to set the base class means bundles can define default hook implementations that do not require configuration. 
Additionally, the bulk of the previous logic for `create_hook_instance` has been moved to a new method called `get_hook_class` which simply returns the class without creating an instance. `create_hook_instance` simply calls `get_hook_class` with the required arguments and then returns the instantiated hook. 
The changes to these methods are reflected in the `bundle` convenience methods that wrap them. 
**NOTE**: I have not written tests for …
> #45998 Adds new hook interface to support custom hook base classes

- python/tank/platform/bundle.py
Noticed we had missed some `base_class` parameters on hook methods so added them + docstrings.
> [minor] Added docstrings

- python/tank/descriptor/io_descriptor/git.py
Addendum. The -C flag was introduced in 1.9 of git. Centos 7 still defaults to 1.8 (released 2013) so for linux this reverts to the old tk approach of setting the current work dir before and after operations.
> #39910 windows using git -C for operations, linux uses just git

- python/tank/commands/constants.py
- python/tank/commands/core_localize.py
- python/tank/commands/setup_project.py
- python/tank/commands/setup_project_wizard.py
- python/tank/constants.py
- python/tank/pipelineconfig_utils.py
- tests/commands_tests/test_setupproject.py
- tests/python/tank_test/mock_appstore.py
This change modifies the `core_localize` command logic, and by proxy the `setup_project` and `setup_project_wizard` commands. Previously, during project setup, the config would be localized if the source config had a local core. This change adds an additional check to `setup_project` to localize using the core specified in `core_api.yml` of the target project (if it exists). If no `core_api.yml` file exists, the previous logic will be used to determine if a localization is required.
In addition, the `setup_project` command's default config has been updated from `tk-config-default` to `tk-config-default2`. 
Adds 2 new methods to `pipelineconfig_utils`: 
- `has_core_descriptor`: Returns `True` if the pipeline configuration contains a core descriptor file
- `get_core_descriptor`: Returns a …
> #35379 Adds localization of config during project setup if `core_api.yml` exists 

- python/tank/pipelineconfig_factory.py
- tests/core_tests/test_pipelineconfig_factory.py
This issue cropped up when working on one project with a classic/installed config. There are scenarios where bootstrap fails while trying to find a config for a given path because other configs are associated with projects that do not have a `tank_name` defined. This is a little fix to bypass trying to associate a path to a config if the config being compared is not classic/installed.
> #46590 Fixes a bug when a site contains configs linked to projects without tank_name defined

- python/tank/platform/bundle.py
- tests/fixtures/config/bundles/test_app/info.yml
- tests/fixtures/config/core/hooks/test_evaluator.py
- tests/fixtures/config/env/post_update/test_post_update_new_parser.yml
- tests/fixtures/config/env/post_update/test_post_update_old_parser.yml
- tests/fixtures/config/env/test.yml
- tests/platform_tests/test_application.py
Fixes a bug which previously prevented the use of procedural hook based evaluation of complex environment properties such as list and strings. Also adds tests for procedural hook based evaluation.
> #46693 Fix for producedural hook evaluation for complex data types

- developer/build_plugin.py
Added the ability to bake a plugin when building it, which can be used to ship a self contained plugin to third party users.
Implemented a workaround for tk-core bootstrap requiring a shotgun.yml file.
> For #46250, --bake option.

- python/tank/authentication/login_dialog.py
JIRA: N/A
DESCRIPTION
This fixes a weird bug on Qt where calling show() and exec_() might lead
to having an invisible modal QDialog and this state freezes the host
application. (Require a `pkill -9 applicationName`). The fix in our case
is pretty simple, we just have to not call show() before the call to
exec_() since it implicitly call show().
This bug is described here: https://bugreports.qt.io/browse/QTBUG-48248
It's a KDE platform bug/limitation and otherwise, it works really well
on other DE ( I tried with Gnome and with XFCE4 ).
TESTS
This dialog might be called on multiple platforms and using multiple Qt
binding (PySide, PySide2, PyQt, PyQt5) and I didn't tested on each
platforms.
DOC
N/A
> Fixes a deadly pattern on KDE

- python/tank/folder/folder_types/entity.py
- python/tank/pipelineconfig.py
- python/tank/platform/bundle.py
- python/tank/util/shotgun/publish_creation.py
- python/tank/util/shotgun_entity.py
- tests/util_tests/test_publish.py
- tests/util_tests/test_shotgun.py
- tests/util_tests/test_shotgun_entity.py
Improvements to folder creation:
- Fixes a bug where projects with a multi-folder tank name didn't publish files correctly
- Adds support for regex patterns and multiple folders for a single schema yaml file. For example:
```
type: "shotgun_entity"
name: "{code:^([^_]+)}/code" # <----- here
entity_type: "Asset"
filters:
- { "path": "project", "relation": "is", "values": [ "$project" ] }
- { "path": "sg_asset_type", "relation": "is", "values": [ "$asset_type"] }
```
This new `{field_name:regex}` syntax is consistent with template regex syntax and allows
for the extraction of subsets from shotgun data and using that in folder creation tokens. 
Also note how the slash in `{code:^([^_]+)}/code` will result in multiple folder levels will be created for this one single schema entry.
> #46177 Multi-path folders, expressions and project root bug fixes.

- python/tank/bootstrap/baked_configuration.py
- python/tank/bootstrap/configuration_writer.py
- python/tank/pipelineconfig.py
Fixes an issue with baked configs where the build-time path descriptor was written into the plugin, causing it to work on the machine where it was built but nowhere else.
> [minor] Baked configs do not write out source descriptor

- python/tank/platform/engine.py
This implements Qt5-specific logic for initializing Toolkit's "dark look and feel."
- Sets the "fusion" style.
- Builds a QPalette that closely follows that of Maya 2017.
- Sets a one-line stylesheet at the application level to correct some styling quirks with the tank dialog's header.
> For #46224: Implements "dark look and feel" for Qt5.

- python/tank/util/constants.py
- python/tank/util/shotgun_entity.py
- tests/util_tests/test_shotgun_entity.py
Fixes two issues with folder creation. Both scenarios are covered with new tests:
- Expressions where the same token appears more than once `{code:^(.)}/{code}` now resolves correctly.
- Expressions with empty folders (`/foo//bar` as opposed to `/foo/hello/bar`) raise a validation error, just like an empty path would.
> #46177 bug fixes for folder creation

- .tkdeploy
- python/tank/descriptor/io_descriptor/shotgun_entity.py
- tests/descriptor_tests/test_descriptors.py
- tests/descriptor_tests/test_downloadables.py
- tests/descriptor_tests/test_shotgun.py
A typical Shotgun descriptor path on Windows would look like this,
`C:\Users\user.login\AppData\Roaming\Shotgun\bundle_cache\sg\PipelineConfiguration.sg_uploaded_config\123/v12345`
which can cause the file length to go over the 260 character limit on Windows.
To solve this, we're making that path a lot shorter by using removing the entity and field name part. This comes at the cost of get_latest_cached_descriptor, which is sorta moot because you need a working Shotgun connection to use a descriptor, so that functionality is essentially useless, since get_latest_cached_descriptor is only meant to be used in offline mode.
> For #46894, shortens the length of shotgun descriptors

- tests/authentication_tests/test_interactive_authentication.py
When running the tests with a PySide-enabled Python, two tests were failing since an internal method was changed to allow the proxy being passed.
Fixed that...
> Fixed UI tests broken after proxy support for SSO

- appveyor.yml
Seems like for some reason environment variables set from the AppVeyor website are not set properly for the `appveyor/pr` builds. Using the secure value inside appveyor.yml instead, which seems to work.
Those variables will not be available from Pull Requests coming from other repos.
> Appveyor PR fix

- python/tank/folder/folder_types/entity.py
- scripts/tank_cmd.py
Adds support for the `Delivery` entity, in folder creation and unregistering.
I have also updated the code to use the field name finding logic from the `tank/utils/shotgun_entity` module so that we have fewer places in our code where we state the entity to field name relationship.
This is based on @reformstudios commit that they provided:
https://github.com/reformstudios/tk-core/commit/770efe47236af9c3f47cff14caa5aca0ddc95719
> #47012 adds Delivery entity support

- python/tank/api.py
Use cases : 
In cases where you have clashing templates, specifically string templates, you may wish to collect all the matching templates to then further filter by template name (eg if 'shot' in template_name, or if 'asset' in template_name). 
This would open up context-specific template searches, or the ability to identify the context of a file simply from a filename, rather than a full path. 
Description:
This update simply abstracts the template search part of template_from_path(path) to allow users to obtain all matching templates from a path, not just one, and more importantly, it does not raise an error if multple paths are found.
> Add templates_from_path function to return multiple templates

- docs/initializing.rst
- python/tank/bootstrap/__init__.py
- python/tank/bootstrap/cached_configuration.py
- python/tank/bootstrap/errors.py
- tests/bootstrap_tests/test_configuration.py
Upgraded the error to it's own exception type so we could catch it explicitly in Shotgun Desktop.
Updated doc:
> For #46757, gentler error when `tank_name` is not set.

- python/tank/util/shotgun/publish_creation.py
Changed string format from %s to .format in the logging message that displays the context.
This was a solution for Alias when the task name contains Chinese/Japanese characters.
> Log the context info using "format" to avoid unicode issues

- tests/run_appveyor.bat
- tests/run_travis.sh
This allows forks to submit PRs that will not immediately fail on submission. We'll need to run the integration tests ourselves before merging however.
> Do not run integration tests from forks

- python/tank/commands/setup_project_params.py
- python/tank/util/storage_roots.py
- tests/fixtures/util/storage_roots/empty_roots/config/core/roots.yml
- tests/util_tests/test_storage_roots.py
The issue was a subtle bug related to populating default values for storage roots. The old core would only do this if there were no roots.yml file. The recent changes were always populating defaults no matter if the file existed or not. Configs like basic and site define this file is empty and don't require storage roots. So populating the roots with a default primary was problematic.
> Hot fix for Desktop error with locked desktopstartup with new core.

- python/tank/platform/engine.py
This contains a minor tweak/hack to make Windows 10 pick the correct font style when font-weight is used in conjunction with Open Sans. We're installing the ttfs for Open Sans in reverse alphanumeric order now, so that the "light" style font is installed before the "condensed light" style. Windows seems to prefer what's installed first when it's determining style based on font-weight settings in qss.
> For SG-4682: [minor] Tweaks to fix Open Sans style on Windows 10 in PySide2.

- python/tank/platform/qt/tankqdialog.py
Sets a bundle's icon at the dialog icon. Seems to work in every DCC except for certain versions of Maya or Mac and Windows (haven't tested Linux).
> For SG-5793, show application icon

- python/tank/util/shotgun/publish_creation.py
- tests/python/tank_test/tank_test_base.py
- tests/util_tests/test_publish.py
Fixes a bug where the logic for splitting paths into storages + normalized path chunks (which are later on passed to the `PublishedFile.path_cache` field) was incorrect if your local storage was a windows drive letter path with no folder (e..g `P:\`). Added tests.
> SG-6314 Fixes bugs in publish path computation

- python/tank/util/shotgun/connection.py
- tests/authentication_tests/test_session_cache.py
- tests/util_tests/test_shotgun_connect.py
We have a situation where some of our code stops functioning properly when Shotgun site urls don't match exactly. This becomes a problem when someone logs into Desktop using `https://SITE.shotgunstudio.com` instead of `https://site.shotgunstudio.com`, and results in most of our apps breaking after launching a DCC. This fix simply lowers the casing of the url when going through our existing sanitization routine.
> For SG-6617: Forces site urls to lowercase to make url comparisons reliable.

- python/tank/descriptor/io_descriptor/git.py
- python/tank/descriptor/io_descriptor/git_branch.py
- python/tank/descriptor/io_descriptor/git_tag.py
This merge request makes git descriptors to use shallow clone whenever possible. It greatly improves clone times, especially with repos with long history. It also uses `git-ls-remote` to get tags without fething it all from remote.
> improve git descriptor performance

- python/tank/bootstrap/async_bootstrap.py
- python/tank/bootstrap/manager.py
* The current implementation doesn't set any parents for any of the QObject/QThread instances created by the async bootstrapper. This causes stability problems in PySide2/Qt5 environments.
* Works around one other crash bug in PySide2/Qt5 environments by not calling a moveToThread in that context.
> SG-8369: Allows a parent to be passed into the async boostrapper.

- docs/core.rst
- hooks/before_register_publish.py
- hooks/bundle_init.py
- hooks/cache_location.py
- hooks/context_additional_entities.py
- hooks/context_change.py
- hooks/engine_init.py
- hooks/ensure_folder_exists.py
- hooks/example_template_hook.py
- hooks/get_current_login.py
- hooks/log_metrics.py
- hooks/pick_environment.py
- hooks/pipeline_configuration_init.py
- hooks/process_folder_creation.py
- hooks/process_folder_name.py
- hooks/resolve_publish.py
- hooks/tank_init.py
- python/tank/hook.py
With the help from this other [PR](https://github.com/shotgunsoftware/tk-internal/pull/28), we can now import the hooks from the hooks folder during documentation generation.
I've polished up the hooks docstrings to bring them at the same level as the rest of our docs.
Download this [zip](https://github.com/shotgunsoftware/tk-core/files/2402261/doc.zip) to see what it looks like. You can reach them by clicking on Core -> Hooks -> Core Hooks.
> For SG-6464, core hooks sphinx documentation

- docs/core.rst
- docs/utils.rst
- python/tank/context.py
- python/tank/util/__init__.py
- python/tank/util/json.py
- tests/core_tests/test_context.py
- tests/util_tests/test_json.py
Introduces two features related to the new publisher API:
- sgtk.util.json.{load,loads}, which are thin wrappers around the Python API and allows to json documents into dictionaries using utf-8 encoded strings.
- sgtk.Context.{to,from}_dict, which allow to serialize/unserialize a context to a dictionary.
> For SG-7259, adds JSON serialization utilities and Context to dict serializer

- python/tank/bootstrap/cached_configuration.py
- python/tank/bootstrap/configuration.py
- tests/bootstrap_tests/test_configuration.py
This fixes a very bad regression introduced by the changes to be able to run a configuration from the bundle cache, which resulted in the cached configuration to be rewritten every single time Toolkit bootstrapped.
This feature has now been thoroughly tested.
> For SG-8646, do not always write configuration on bootstrap

- .travis.yml
- python/tank/bootstrap/baked_configuration.py
- python/tank/bootstrap/configuration_writer.py
- python/tank/commands/setup_project_wizard.py
- tests/bootstrap_tests/test_configuration.py
Baked configs built into an sgtk plugin don't really need to contain install_location.yml, interpreter_*.cfg, and the tank command to function. However, we have some logic in places like the setup project wizard and core localization where the current config (which might be baked) is introspected in ways that require these files exist. This change ensures that they're created when an SGTK plugin is built with a baked config.
> SG-3025: Ensures that some supplementary config files exist in baked configs.

- python/tank/path_cache.py
- tests/core_tests/test_path_cache.py
Path caches for descriptor-based configurations will now NOT use the `plugin_id` in the folder suffix for the path cache.
This will allow reuse of the path cache between DCCs that use the same pipeline configuration and project, requiring less syncs of the path cache. It also fixes an issue when launching apps in an asset or task context from Shotgun.
> For SG-8449, path cache sandboxing fix

- developer/utils/authentication.py
When running the script `populate_bundle_cache.py`, I discovered that the logger message was not correct, because it was saying that the Shotgun Host is None.
This message is generated in the authentication utility. The issue was that the `options.shotgun_host` variable was used instead of `shotgun_host`
This is an example of the current console and log file output message
> Fixes logger message in the developer authentication utility when connecting to SG Host

- .travis.yml
Do not run coveralls if tests weren't run. This seems to confuse coveralls.
> [minor] Fix coverage report on coveralls.

- python/tank/platform/engine.py
- python/tank/util/shotgun/publish_creation.py
- tests/util_tests/test_publish.py
Catches the Attachment.local_storage error and raises a more meaningful error message.
This is how the error shows up in the publisher. Ideally we would get better formatting in the app itself.
> For SG-9118, better handling of local file linking errors when publishing

- python/tank/hook.py
In `def run_action(self, action, sg_publish_data)`, `action` comes before `sg_data`
> Change order of execute_hook_method's parameters in doc

- python/tank/commands/validate_config.py
- tests/commands_tests/test_validate.py
`tank validate` was recently broken in [this](https://github.com/shotgunsoftware/tk-core/commit/a1ef81d6a667954d585933ef78a3ebb1f217a965#diff-f42a05817c04a0145683452a91722c3bR101) update, causing the following error:
```
ERROR: A general error was reported: _process_environment() takes exactly 4
arguments (5 given)
File "/sg_toolkit/greyhounddev.shotgunstudio.com/configs/new_config_project/install/core/scripts/tank_cmd.py", line 1630, in <module>
exit_code = run_engine_cmd(pipeline_config_root, ctx_list, cmd_name, using_cwd, cmd_args)
File "/sg_toolkit/greyhounddev.shotgunstudio.com/configs/new_config_project/install/core/scripts/tank_cmd.py", line 1290, in run_engine_cmd
return run_action(logger, tk, ctx, command, args)
File …
```
> SG-9978 fixes a bug with "tank validate".

- docs/authentication.rst
- python/tank/authentication/__init__.py
- python/tank/authentication/console_authentication.py
- python/tank/authentication/errors.py
- python/tank/authentication/login_dialog.py
- python/tank/authentication/shotgun_authenticator.py
- python/tank/authentication/sso_saml2/__init__.py
- python/tank/authentication/sso_saml2/core/sso_saml2_core.py
- python/tank/authentication/sso_saml2/core/utils.py
- python/tank/authentication/sso_saml2/sso_saml2.py
- python/tank/authentication/sso_saml2/sso_saml2_rv.py
- python/tank/authentication/sso_saml2/utils.py
- python/tank/authentication/user.py
- python/tank/authentication/web_login_support.py
- python/tank/bootstrap/configuration.py
- tests/authentication_tests/test_interactive_authentication.py
- tests/authentication_tests/test_shotgun_authenticator.py
- tests/authentication_tests/test_user.py
Given that the SAML login flow and the new Unified Login Flow were very similar, we have updated the existing code base to support the ULF. As with SSO, a Web-browser Qt object (WebKit/WebEngine) is used for the authentication.
This required the addition of a new outside-world exposed class: ShotgunWebUser. This is in order to leverage the existing session_metadata structure (which contains the serialized cookies of the Web-browser used for authentication). This is to support re-authentication.
The existing ShotgunSamlUser class becomes a specialized version of ShotgunWebUser, which provides the Claims Renewal functionalities.
For pre SG 8.0 sites which uses default authentication mode or LDAP, the same existing GUI will be presented (Console and QApplication).
For sites using SSO or …
> For SG-8310: initial support for Unified Login Flow

- python/tank/context.py
- tests/core_tests/test_context.py
On Windows, when Python 2.7.14 is used, we could get ourselves into an infinite loop if a project's root was at the root level of a UNC path.
Worked fine: `\\foo\projects\my_project_root_folder\`
Didn't work fine: `\\foo\my_project_root_folder\`
The crux of the issue is that something changed in Python that causes the trailing path separator to remain when `os.path.dirname` is called on the root folder of a UNC path, while it used to be chopped off:
Old return value: `\\foo\my_project_root`
2.7.14 return value: `\\foo\my_project_root\`
The trailing path separator caused some parsing logic we have to not recognize the path as the project root, and we ended up in an infinite loop as a result.
> SG-10167: Fixes an infinite loop on Windows.

- python/tank/descriptor/io_descriptor/base.py
- python/tank/platform/environment.py
- tests/run_appveyor.bat
Currently, if you use the disable or deny_platforms setting on a location descriptor then it will give you are warning that these parameters are unsupported and won't be used, despite the fact that they are supported and will be used in deciding is an item is disabled or not.
```
[81012 WARNING sgtk.core.descriptor.io_descriptor.base] Found unsupported parameters set(['disabled']) in {'disabled': False, 'path': '/path/to/app', 'version': 'v5.6.9', 'type': 'dev'}. These will be ignored. 
```
Although the descriptors themselves don't make use of these parameters they are in fact looked for and used here: 
https://github.com/shotgunsoftware/tk-core/blob/master/python/tank/platform/environment.py#L108-L126
Arguably the parameters perhaps shouldn't be part of the location descriptor in the …
> SG-12281 Makes the disable and deny_platforms valid optional parameters

- python/tank/platform/engine.py
If you are using a distributed config and push an updated config to the cloud, when a client bootstraps and it attempts to update to the latest config on Windows there is a chance that it won't update and will silently just load up the previously cached config with no warning at all to the user.
The problem is that a TD will push a config with updates and fixes to the artists, and ask them to reload their project, and they think everything is fine until they realise the fixes haven't been applied. The workaround currently is to ask the user to log out and back in at a OS level.
It turns out that QT keeps open file handles to the font files we provide, thereby preventing the bootstrap from moving the old core into a backup location at runtime.
This fix tweaks the font loading so that fonts …
> SG-12126 - Fixes bug where bootstrap fails to auto update.

- .travis.yml
- tests/run_travis.sh
Travis deprecated the way we were starting XVFB for Xenial dist, which is now the default.  To work around this, we needed to switch to the new syntax described [here](https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-services-xvfb).
> Fixes failures on travis CI related to starting XVFB

- python/tank/authentication/sso_saml2/core/sso_saml2_core.py
- python/tank/authentication/sso_saml2/core/username_password_dialog.py
Following comments from JF, Manne, Rob and Florencia, I have updated the dialog to be more helpful and to respect the toolkit style more closely.
Qt4 version:
Qt5 version:
> Updated look-and-feel of the SSO authentication dialog

- python/tank/bootstrap/import_handler.py
- tests/fixtures/config/bundles/simple_test_app/app.py
- tests/fixtures/config/bundles/simple_test_app/info.yml
- tests/integration_tests/data/simple_config/core/core_api.yml
- tests/integration_tests/data/simple_config/env/project.yml
- tests/integration_tests/data/site_config/core/core_api.yml
- tests/integration_tests/data/site_config/env/project.yml
- tests/integration_tests/multi_bootstrap.py
- tests/integration_tests/offline_workflow.py
- tests/integration_tests/run_integration_tests.py
This fixes integration tests for the Python 3 branch. Here's what was fixed:
- The one big issue was with the core swapper, whose import handler was not getting invoked in Python 3. I've fixed the issue and documented the fix.
- The rest of the changes was fixing laziness on our part when I wrote these tests originally, which introduced dependencies on tk-config-basic. This causes a problem at the moment because none of the apps are Python 3 compatible and this broke the tests when loading engines and apps. Therefore, I've fixed the tests so that the repo is self-contained and does not pull a config from another repo.
- I introduced a simple app that doesn't require any configuration that can be used in any test.
- Integration tests can now be run individually.
> SG-13264: python 3 compat integration tests

- python/tank/util/metrics.py
Manne had already done the work to send these metrics to Amplitude by way of tk-core, but he hadn't whitelisted the event name, which resulted in an "Unknown event" being logged. This is just whitelisting the one new event name he added to tk-desktop2.
> SG-13074: Adds "Executed websockets command" to the list of known event names

- .flake8
This warning emitted by flake8 will not be a warning in the future and will become the new best practice according to pep8. `black` already fixes code by using the new rule, which is causing errors in HoundCI on our repos that are being converted to the `black` code style. This will silence this error.
To learn more about this warning, see this: https://lintlyci.github.io/Flake8Rules/rules/W503.html
Note that this file is actually used by all our repo's when it comes to HoundCI, not just tk-core, which is why it's important to fix the problem here.
> Silences flake8 on W503 errors

- python/tank/folder/folder_io.py
- python/tank/path_cache.py
- python/tank/template.py
- tests/folder_tests/test_create_folders.py
- tests/folder_tests/test_task_node.py
The PR fixes an issue with the Task folder creation. 
Before this fix it would create two registries for for each generated task node path. Each would have the same path but one was registered to the Task as a primary path and the other was registered to the Step as a secondary entity.
During the registry it would first create the path_cache rows, and then the `FilesystemLocation` entities, and finally it would fill in the shotgun_status table in the local cache with a map of the relationships between the path_cache table and the FilesystemLocation entities.
The problem is that when it tried to map the created FilesystemLocation entities to the local path_cache table's row ids it only checked paths, and since the task folder generates two records with the same path, it wasn't correctly …
> SG-14303 Added a fix and tests for Task folder creation,

- python/tank/platform/environment_includes.py
- python/tank/template_includes.py
- tests/core_tests/test_includes.py
This merges a fix from the automotive team that ensures includes from environment files are always returned in the order they were found in the file.
I've added a test.
The use of a set to keep track of which files were visited screwed up the ordering of the includes because sets sort their input. The fix reverts the code back to using a list as it originally was and uses the in operator to exclude files.
> SG-6255: Include files order

- python/tank/util/pyside2_patcher.py
The bug is present in some releases of PySide2 5.12.x. In the case where we see the exception raised, we've determined that it's safe to return the wrapped method as is, without the decoration provided by the update_wrapper call that's caused the exception.
> SG-14324: Works around a shiboken2 bug

- tests/fixtures/util_tests/json_saved_with_python_2.json
- tests/fixtures/util_tests/json_saved_with_python_3.json
- tests/util_tests/test_json.py
This test proves JSON can be reloaded as is across Python versions.
> SG-13264: json serialization

- python/tank/authentication/user.py
- python/tank/authentication/user_impl.py
- python/tank/context.py
- tests/core_tests/test_context.py
The API feels saner this way. The default behaviour is the same as before, but you get JSON by "asking for JSON" instead of "asking not to pickle".
Also, added test!
> SG-13264: fixing context.serialize signature

- python/tank/log.py
- tests/core_tests/test_log.py
Fixes a warning printed to the console when logging unicode from Toolkit. On Windows with Python 3, the serializer is picky on the output format so we'll have to override the default.
> SG-15468: logging unicode fix

- .pre-commit-config.yaml
- python/tank/api.py
- python/tank/template.py
- python/tank/util/shotgun/publish_creation.py
- tests/core_tests/test_api.py
- tests/core_tests/test_templatepath.py
- tests/fixtures/config/core/templates.yml
- tests/util_tests/test_shotgun_publish_creation.py
When using templates with abstract keys that are optional such as
```python
{name}[.{frame}].{ext}  #Where frame is a SequenceKey with the implicit default value of %d
```
The `tk.paths_from_template` and the `publish_creation._translate_abstract_fields` methods were returning incorrect or missing values. This solves the problem by adding an option to `template.apply_fields` to not use default values for optional keys. The two methods above can then use the new signature to function correctly.
> SG-15803 Bugs with Optional Abstract Keys

- python/tank/context.py
- python/tank/util/sgre.py
- tests/core_tests/test_context.py
- tests/util_tests/test_sgre.py
In Python 3 if `__eq__` is defined for a class, that class no longer inherits `__hash__` from its parent.  This defines `__hash__` on Context to ensure that Contexts are hashable in Python 3.
> Make Context hashable in Python 3

- developer/bake_config.py
- developer/build_plugin.py
- developer/populate_bundle_cache.py
- developer/utils/authentication.py
- developer/utils/caching.py
Some enhancements on top of https://github.com/shotgunsoftware/tk-core/pull/650.
There is now a warning when a dev/path descriptor will not be cached. Bundles are only processed once.
```
'{'path': '$DEV_ROOT/gitlocal/tk-multi-breakdown', 'type': 'path'}' will not be cached inside the configuration.
```
> SG-7627: Merge bake config script

- docs/utils.rst
- python/tank/util/unicode.py
- tests/util_tests/test_unicode.py
This ensures that pickles of tuples are properly converted to ensure utf-8 encoded `str` objects are found in the unpickled data instead of Python `bytes`.
> SG-14617: fixes for Python 3 port of tk-desktop

- python/tank/platform/environment.py
- tests/fixtures/config/env/invalid_settings/empty_app_location.yml
- tests/fixtures/config/env/invalid_settings/empty_app_settings.yml
- tests/fixtures/config/env/invalid_settings/empty_engine_location.yml
- tests/fixtures/config/env/invalid_settings/empty_engine_settings.yml
- tests/fixtures/config/env/invalid_settings/empty_framework_location.yml
- tests/fixtures/config/env/invalid_settings/empty_framework_settings.yml
- tests/fixtures/config/env/invalid_settings/missing_app_location.yml
- tests/fixtures/config/env/invalid_settings/missing_engine_location.yml
- tests/fixtures/config/env/invalid_settings/missing_framework_location.yml
- tests/platform_tests/test_environment.py
Added validation and better error reporting for the engine/app/framework settings dict in the environment file
For example if you don't define the "tk-multi-workfiles2" location in your env you used to get:
and now the error looks like:
> SG-16672 Better error reporting for missing location key

- python/tank/util/metrics.py
Fixes a bug with Python 3 where metrics weren't logged.
The urlopen method was being passed a str payload rather than a bytes.
> Fixes broken metrics in Python 3.

- setup.py
By default, subprocess.check_output returns bytes, which causes `python setup.py egg_info` to fail with a stack trace, like this:
```
% python setup.py egg_info                            
/Users/garyo/Library/Caches/pypoetry/virtualenvs/deliverables-nQKiRMb9-py3.7/lib/python3.7/site-packages/setuptools/dist.py:483: UserWarning: The version specified (b'v0.19.5') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
"details." % self.metadata.version
running egg_info
File "setup.py", line 84, in <module>
package_dir={"": "python"},
File "/Users/garyo/Library/Caches/pypoetry/virtualenvs/deliverables-nQKiRMb9-py3.7/lib/python3.7/site-packages/setuptools/__init__.py", line …
```
> setup.py: decode git version output to string for py3

- setup.py
Fixes an issue reading version information when running setup.py under Python 3.
This applies the fix submitted to us by https://github.com/shotgunsoftware/tk-core/pull/760 and runs black on top of it.
> [minor] setup.py fix for Python 3

- python/tank/util/shotgun_entity.py
The tank.util.shotgun_entity.get_sg_entity_name_field() method does not currently account for the relatively new "Tag" entity.  It is currently returning 'code', but should return 'name'.
> get_sg_entity_name_field() returning bad value for Tags

- python/tank/platform/engine.py
When using `sgtk.platform.find_app_settings()` it used to just catch all app setting validation errors silently and not give any feedback on why settings were not available.
This PR logs an exception now:
```
engine: Warning: Could not validate app settings for the "tk-multi-pythonconsole_bad" app instance in the "project" environment on the tk-desktop "engine".
File "/Users/bob/Library/Caches/Shotgun/mysite/p89c1.basic.shell/cfg/install/core/python/tank/platform/engine.py", line 3243, in find_app_settings
validation.validate_settings(app, tk, None, schema, settings)
File "/Users/bob/Library/Caches/Shotgun/mysite/p89c1.basic.shell/cfg/install/core/python/tank/platform/validation.py", line 51, in validate_settings
v.validate(settings)
File …
```
> SG-16901 log an exception when running find_app_settings and invalid

- python/tank/bootstrap/configuration_writer.py
- tests/bootstrap_tests/test_configuration_writer.py
Fixes an issue where if a user had an apostrophe in their name the configuration_writer.yml file would get corrupted when using distributed configurations.
> SG-4562: apostrophe in config path fix

- python/tank/platform/qt/tank_dialog.ui
- python/tank/platform/qt/ui_tank_dialog.py
In Nuke 12.1 the header of the core app widget (that all app dialogs get grouped under) became squashed. The Shotgun logo and title didn't display correctly.
This fix ensures it stays looking the same across all host software.
> SG-17126 Fixes a styling issue that appears in Nuke 12.1.

- python/tank/util/pyside2_patcher.py
In PySide2 you would get duplicate Yes/NoToAll buttons if you passed them as flags to a question constructor, due to a bug in our shim.
This fixes the shim and also limits it's use to pre PySide2 v5 versions.
> SG-17357 fix for Qmessagebox duplicate buttons.

- tests/integration_tests/bootstrap_hook.py
We often get connection reset by peer during this test on Azure Pipelines during the upload. This should harden the test against upload failures.
> Integration test hardening.

- python/tank/descriptor/io_descriptor/appstore.py
- python/tank/util/shotgun/download.py
Defines environment variable that can be used to set a custom app store URL for testing purposes.
> SG-17895 define custom app store url

- python/tank/authentication/sso_saml2/core/sso_saml2_core.py
By creating an alias to the original function definition, we triggers Babel (if used) to NOT to polyfill with its own version.
That check to see if the method needs to be polyfilled cause the virtual machine to go into an infinite loop.
> For SG-18321: redefine Array.prototype.splice as an alias to itself

- python/tank/descriptor/io_descriptor/path.py
This change allows the use of environment variables when specifying the version in a path descriptor. For example you could do the following:
```
base_configuration:
type: path
path: "${CONFIG_PATH}"
version: "${CONFIG_VERSION}"
```
We don't explicitly use the `version` field in a path descriptor so this will not affect any regular descriptors. The only place this will be useful is when baking a configuration and we need to provide a descriptor to the bake script that includes an environment variable. 
**For testing:**
- Create a folder for your test plugin
- Inside the folder place an `info.yml` file that contains the following:
```
base_configuration:
type: path
path: "${CONFIG_PATH}"
version: "${CONFIG_VERSION}"
plugin_id: "basic.test"
```
- Set the env var `CONFIG_PATH` in your …
> Allow Env Vars in Path Descriptor Version Spec

- docs/utils.rst
- python/tank/util/__init__.py
- python/tank/util/version.py
- tests/util_tests/test_version_compare.py
In some parts of the Toolkit platform, we compare the version of a bundle with a specific known version to know if a certain feature is available or not. This becomes an issue when the bundle is a git_branch descriptor, because the version is then a git hash.
Now, when a git-hash is detected in the `is_version_` methods, we consider them more recent than whatever was the other value passed in. More helpers were also added to simplify writing code.
Finally, those methods are now part of the official Toolkit API and can be used by anyone.
Here's what the doc looks like:
This is a pre-requisite for https://github.com/shotgunsoftware/tk-framework-desktopstartup/pull/61
> SG-18533: Comparing a git hash with a version string raises an error in Python 3.

- docs/authentication.rst
- python/tank/authentication/__init__.py
- python/tank/authentication/errors.py
- python/tank/authentication/user.py
- python/tank/authentication/user_impl.py
- tests/authentication_tests/test_user.py
We can now resolve the Shotgun entity for a given `stgtk.authentication.ShotgunUser`. If we can't resolve the user, the `UnresolvableScriptUser` or `UnresolvableHumanUser` error is raised.
Here's what the new doc looks like.
In the ShotgunUser class:
The documentation for the exceptions was too verbose. They didn't have members and we shouldn't have displayed methods from the base class.
> Automation helpers

- tests/integration_tests/data/simple_config/env/project.yml
- tests/integration_tests/tank_commands.py
App store and git setup project tests now use a new dedicated simple testing config, which means testing time is a lot faster due to less dependancies.
https://github.com/shotgunsoftware/tk-config-testing
Previously the tests were failing because the size of one of the basic config components was very large and it timed out waiting for the setup project to complete due to the download time.
Also removes a skip, now that tk-shell is Python 3 compatible.
Updates the test config components, but not to the latest so that the update test can still run.
> SG-19670 Fixes the integration tests by using a simple test config.

- python/tank/util/filesystem.py
There were multiple complaints from ACD customers about poor performance during Shotgun Publishing in Alias and VRED which led to this backlog ticket. After investigating, this tweak to the copy operation greatly improves the performance.
> [SHOT-3594] Windows platform shutil buffer override to increase performance for file copying

- python/tank/bootstrap/manager.py
- python/tank/platform/__init__.py
- python/tank/platform/engine.py
- python/tank/platform/environment.py
- python/tank/platform/errors.py
Distinguishes between generic engine bootstrap failure and getting None from the pick_environment hook.
Desktop server can then handle this case differently from other engine bootstrap failures. ([PR for desktopserver](https://github.com/shotgunsoftware/tk-framework-desktopserver/pull/79))
> Gracefully dealing with pick_environment returning None

- python/tank/authentication/console_authentication.py
- python/tank/authentication/login_dialog.py
- python/tank/authentication/session_cache.py
- python/tank_vendor/shotgun_api3/shotgun.py
- tests/authentication_tests/test_interactive_authentication.py
The tk-core code had unfortunately not been updated since the decision to add Personal Access Tokens has been made.
Previously, Autodesk Identity suffered the same constraint as logging in with a SSO-enabled site: you needed to use a  Browser-like environment to authenticate
But with the addition of PATs to Autodesk Identity, the old-style username / password (now known as Legacy Username / Passphrase) can also be used to authenticate. This allows existing code to handle Autodesk Identity authentication on sites that have migrated.
Screenshot showing the before/after for a console-based script:
As can be seen on the first attempt, just the fact that we detect that the site is using Identity is enough to stop the authentication process. The second attempt works, showing the list of …
> For SG-23187: Fixed authentication for Autodesk Identity

- python/tank/authentication/login_dialog.py
With SG-18096 we want to set the Web login mode as the default mode for all sites, no matter what their authentication mode is. Previously, only when login to a SSO or Autodesk Identity site would the Web login mode be used.
Some users will need to use the old Qt dialog, in order to:
circumvent graphical issues with Qt and the WebEngine
need to authenticate with the site using their Personal Access Token
desire a more controlled roll-out of the Web login mode for sites still using the default ShotGrid
By setting the environment variable `export SGTK_FORCE_STANDARD_LOGIN_DIALOG=1`, the toolkit will instead default to the old-style Qt dialog if connecting to a default or Autodesk Identity site.
Without environment variable:
With environment variable set:
> For SG-23615: provide override to use the old Qt authentication dialog

- python/tank/descriptor/io_descriptor/git.py
- python/tank/descriptor/io_descriptor/git_branch.py
- python/tank/descriptor/io_descriptor/git_tag.py
- python/tank/util/version.py
- tests/integration_tests/tank_commands.py
Reviewing the client PR about shallow git clones using git descriptors because it was not properly sorting the git tag versions with dashes appended.
> SG_7624 Review client PR Shallow git clones using git descriptors

- docs/environment_variables.rst
- python/tank/authentication/sso_saml2/core/sso_saml2_core.py
With Autodesk Identity being now used for hosted ShotGrid sites, we have added new environment variables to help improve the authentication flow.
The environment variable `TK_SHOTGRID_DEFAULT_LOGIN` can be used to set the Autodesk Identity username, an email. It will be used to pre-fill the email field.
Example: `export TK_SHOTGRID_DEFAULT_LOGIN=user@example.com`
The environment variable `TK_SHOTGRID_SSO_DOMAIN` can be used to indicate the email domain associated to Autodesk Identity for the SSO login (requires a Premier Subscription). This allows the user to bypass the initial Autodesk Identity login page and go directly to their company SSO system. If the domain set is NOT associated to SSO, then the normal Autodesk Identity flow will be used.
Example: `export …
> For SG-24624: allow tk-core to improve the Autodesk Idenity login UX

- docs/environment_variables.rst
- python/tank/bootstrap/constants.py
- python/tank/bootstrap/manager.py
- tests/bootstrap_tests/test_manager.py
This PR reverse the 'SGTK_CONFIG_LOCK_VERSION' envvar logic that was introduced in this [PR](https://github.com/shotgunsoftware/tk-core/pull/854) , these changes will be updated again in a new PR when it is decided to remove Python 2 support.
> Reverse the 'SGTK_CONFIG_LOCK_VERSION' envvar logic 

- python/tank/authentication/sso_saml2/core/sso_saml2_core.py
- python/tank/authentication/sso_saml2/core/utils.py
- tests/authentication_tests/test_saml_sso_core_utils.py
I validate that unquote_plus exist both in python 2 and 3...
https://docs.python.org/2/library/urllib.html#urllib.unquote_plus
https://docs.python.org/3/library/urllib.parse.html#urllib.parse.unquote_plus
I also fix a small typo...
> SG-28499 - Fix sso_saml2 login error when login contain a space

- .gitignore
- python/tank/platform/qt/tankqdialog.py
To ensure type safety, dict `get` value now returns a `"None"` string to keep backwards compatibility and prevent crash use case introduced on #865.
- Switch "modulo" interpolation for `format` method while building the tooltip.
- Applied `black` formatter to the source file.
> SG-29808 Remove six.ensure_str to formatter function

- python/tank/util/pickle.py
- tests/util_tests/test_unicode.py
```
File "/xxx/cfg/install/core/python/tank/util/pickle.py", line 54, in dumps
return six.ensure_str(serialized)
File "/xxx/cfg/install/core/python/tank_vendor/six.py", line 900, in ensure_str
s = s.decode(encoding, errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfd in position 159: invalid start byte
```
There can be also 'invalid start byte" error in pickle.dumps!
Consider also removing the reason check
```
if e.encoding == "utf-8":
```
> SG-30639 fix: utf-8 in pickle dumps

- python/tank/authentication/console_authentication.py
- python/tank/authentication/constants.py
- python/tank/authentication/login_dialog.py
- python/tank/authentication/session_cache.py
- tests/authentication_tests/test_interactive_authentication.py
Code refactoring to make the `ConsoleAuthenticationHandler` class support more than one "method/UX".
Before that, the class only supported legacy login/password authentication. The "embedded web browser" (unified login flow) method was not supported and remains so. This is not possible because the console handler does not have QT available so can not raise the QT-based web browser.
Insert a command line dialog to have the user select its authentication UX between login/password and ULF2 when both options are available. When this is the case, the user's choice is saved in the session cache using the same setting as the QT login dialog.
When the user selects the ULF2 method, instructions are displayed in the terminal first. Then, after the user press [enter], the web browser is launched the …
> SG-30914 Implement the App Session Launcher authentication UX in the console handler

- python/tank/authentication/sso_saml2/utils.py
- tests/authentication_tests/test_interactive_authentication.py
_unified_login_flow_enabled**2**_ ->  _unified_login_flow**2**_enabled_
Includes retro-compatibility for using the typoed setting name
> SG-31204 Fixup wrong setting name

- .flake8
- python/tank/util/yaml_cache.py
This pr fixes the 'UnicodeDecodeError' when using using non utf-8 special encoding standards.
> SG-30649 Specify 'utf8' encoding when read YAML data from disk.

- python/tank/platform/engine.py
- python/tank/platform/qt6/__init__.py
- python/tank/util/pyside6_patcher.py
- python/tank/util/qt_importer.py
* Provide a patch for PySide6 to work using the PySide (Qt4) interface
* Create a new qt6 module to import PySide6 directly (unpatched)
* Next step, deprecate PySide/Qt4 and make PySide6/Qt6 the default base
> SG-30534: First step to supporting PySide6

- python/tank/authentication/login_dialog.py
Passing the parent parameter in the constructor created a crash when using Nuke.
> SG-31206 Fixup crash with Nuke

- python/tank/util/yaml_cache.py
This PR keeps the support for Python 2 and fix the issue when launching Python 2 DCC's from SG Desktop.
> [Config 1.6.0 rc3] Some DCC versions will not launch Shotgrid

- python/tank/authentication/login_dialog.py
This PR fixes the issue introduced in tk-core v0.20.21 happening on Windows where the QMessageBox confirmation dialog is hidden in the foreground behind the new SG Desktop login dialog, making it not visible and not actionable.
> SG-31666 - Force the QMessageBox to be on top.

- python/tank/authentication/login_dialog.py
- python/tank/authentication/sso_saml2/utils.py
- python/tank/authentication/unified_login_flow2.py
ShotGrid version >=8.53.0.1993. now provide the browser URL so we no longer need to format it from the given information.
> SG-31705 - The API now provide the URL so no need to format it ourselves

- python/tank/authentication/console_authentication.py
- python/tank/authentication/login_dialog.py
- python/tank/authentication/unified_login_flow2.py
- tests/authentication_tests/test_ulf2.py
Updated the new **Unified Login Flow 2** process to detect and send an accurate _Application Name_ to ShotGrid instead of the hardcoded "Toolkit".
There are 4 alternatives for selecting the name (priority with the following as the first match returns):
1. pass by the environment with `TK_AUTH_PRODUCT`
2. use the current_engine if defined (with an exception for the "desktop" engine)
3. detect if ShotGrid Desktop by scanning `argv[0]`
4. default to `ShotGrid Toolkit` if can't find something better...
> SG-30915 Detect the application name sent to ShotGrid

- python/tank_vendor/ruamel_yaml/comments.py
- python/tank_vendor/ruamel_yaml/constructor.py
- tests/descriptor_tests/test_github.py
- Python 3.10 deprecation notice
```
##[warning]Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
```
- Python 3.9 tempfile mocker class
```
##[warning]Exception ignored in: <function _TemporaryFileCloser.__del__ at 0x10e04b310>
```
> SG-31939 Remove warnings raised by CI tests

- python/tank/authentication/console_authentication.py
- python/tank/authentication/login_dialog.py
- python/tank/platform/engine.py
- python/tank/util/metrics.py
- python/tank/util/metrics_cache.py
- tests/util_tests/test_metrics_cache.py
Send metrics to ShotGrid regarding the authentication experience. This includes:
- user_authentication_method (default, oxygen, saml, ...)
- auth UX (basic login/password, web login, local browser)
- client UI (qt_dialog, console)
- renewal (true/false)
This way, we should be able to measure the adoption of the new authentication mechanism.
> SG-30916 Log Metrics regarding the authentication experience

- python/tank/util/pyside6_patcher.py
- python/tank/util/qt_importer.py
- tests/python/tank_test/tank_test_base.py
- tests/util_tests/test_pyside6_patcher.py
- tests/util_tests/test_qt_importer.py
* QPalette.Background is now removed in Qt6. Use QPalette.Window instead (as per Qt doc)
* Revert PySide import ordering in QtImporter to try to import PySide2 first and PySide6 last
> SHOT-4293: Fix PySide6 patch for QPalette.Background and PySide import ordering

- python/tank/util/version.py
- tests/util_tests/test_version_import.py
* VRED cannot run ShotGrid because it fails on import for setuptools (see more details [here](https://jira.autodesk.com/browse/VRED-21235))
* Modify logic to try to import distutils from setuptools regardless of python version, with fallback to old import way if it fails
> Bug Fix:  Import setuptools

- python/tank/authentication/shotgun_authenticator.py
Allows callers of get_user_from_prompt to override the `host` `login` `http_proxy` and `is_host_fixed` for specific calls. 
This is required for RV's new login mechanism to reach feature parity with the previous login. 
`host` allows a default value to be set to in the host entry the prompt.
`is_host_fixed` enables the login to be forced to that host. 
`http_proxy` and `login` are added for consistency.
> SG-33958 - Allow overrides to get_user_from_prompt

- python/tank/authentication/session_cache.py
Prevent ShotGrid Desktop from crashing when the current user's session_token key is missing from the session_cache.
> SG-33787 & SG-34012 Fix session token exception

- python/tank/authentication/login_dialog.py
- python/tank/authentication/session_cache.py
The session_cache initializes default values for some keys. We don't want or need to have a null default value for the authentication method.
> SG-33967 Avoid storing null default value in session cache for the authentication method

- docs/descriptor.rst
Preview:
Both functions points to the standard Python docs: 
- https://docs.python.org/3.9/library/os.path.html#os.path.expanduser
- https://docs.python.org/3.9/library/os.path.html#os.path.expandvars
> SG-33048 Update dev and path descriptor docs

- docs/environment_variables.rst
- python/tank/authentication/login_dialog.py
On RV, we have the RV_SHOTGUN_AUTH_NO_HTTPS environment variable. We lost that functionality while moving to a login based on SGTK.
> SG-34181 Allow http:// sites with an opt-in environment variable

- python/tank/authentication/site_info.py
- tests/authentication_tests/test_interactive_authentication.py
Some logs are now ignored when the user is starting to type `https` on the login dialog to have a cleaner tk-desktop.log file.
> SG-33968 Hide logs when user is typing https on login dialog

- python/tank/util/pyside6_patcher.py
the QWheelEvent::delta method is currently used in tk_multi_pythonconsole/python/app/input_widget.py and output_widget.py
> Add PySide6 patch for QWheelEvent::delta method (SG-31831)

- python/tank/util/pyside6_patcher.py
This PR fixes the issue that was affecting the ShotGrid Snapshot 'Take Screenshot' feature in Maya Beta 2025.
- Adds a no-op patch for the obsolete PySide `QCoreApplication.flush()` method to maintain compatibility with older PySide references to the flush method, this ensures that calls to `flush()` do not cause errors when using PySide6.
> SG-33587 Fix compatibility with PySide6 by patching QCoreApplication.flush()

- python/tank/platform/engine.py
- python/tank/util/qt_importer.py
- tests/util_tests/test_qt_importer.py
This PR enhances the `sgtk.platform.qt` module by enabling direct access to the appropriate `shiboken` module based on the PySide version in use.
> SG-34534 add shiboken module to tk core qtimporter class

- python/tank/authentication/console_authentication.py
- tests/authentication_tests/test_interactive_authentication.py
* Fix regression: re-enable login/password authentication for oxygen/identity
Regression introduced by #890
* Set ASL the default method for console - Should have been done in #948
* Fix an error when console authentication failed
> SG-35085 Make sure login/password authentication is available in console mode

- python/tank/descriptor/io_descriptor/appstore.py
- scripts/tank_cmd.py
- tests/descriptor_tests/test_descriptors.py
Sometimes we have support cases with messages like:
```
[33532 DEBUG sgtk.core.descriptor.io_descriptor.appstore] ...could not establish connection: 'SSLCertVerificationError' object has no attribute 'message'
```
```
File "C:\Users\xxxxxxxx\cfg\install\core\scripts\tank_cmd.py", line 1494, in run_engine_cmd
'"tank unregister_folders /path/to/folder"' % exc.message
AttributeError: 'TankInitError' object has no attribute 'message'
```
Turns out tk-core is raising an error the moment the error is handled. 
This PR attempts to fix this by gracefully getting the error description.
> SG-35087 Stop masking exceptions

- python/tank/descriptor/io_descriptor/git_branch.py
This missing import could mask other handled errors.
> SG-31445 Add missing import TankGitError

- python/tank/util/pyside6_patcher.py
> SG-35318 Add default argument to anonymous function

- python/tank/util/pyside6_patcher.py
Assures `QIcon.pixmap` method always returns an instance of the patched `QPixmap` class.
> SG-35252 Patch QIcon method

- python/tank/util/qt_importer.py
Code refactoring to make it clear which Qt interface we try to load and the strategies we apply for each version.
I don't expect any behavior difference with this change.
conflict with #973
> SG-27840 - SG-30560 - Make the QtImporter logic easier to read

- python/tank/platform/engine.py
Qt6 accepts the same styling as Qt5, so we're reusing the Fusion style when running on Qt6.
Testted with tk-multi-demo. It doesn't need default styling per app anymore.
> SG-35349 Initialize the dark look and feel for Qt6

- python/tank/authentication/login_dialog.py
This link is not accurate when using other authentication methods.
> SG-30760 Make the "Forgot your password" link visible only when using legacy auth methods

- .pre-commit-config.yaml
- developer/build_plugin.py
- scripts/tank_cmd.py
Cleanup and update `.pre-commit-config.yaml` file:
- Update pre-commit-hooks to version `v5.0.0`
- Update black hook to version `25.1.0`
- Update black hook URL
- Use global `default_language_version` instead of individuals `language_version`
These changes are optional considering shotgunsoftware/tk-ci-tools#58. But we might want to cleanup/update the `.pre-commit-config.yaml` file every once in a while.
> SG-33057 update pre commit hook versions

- python/tank/util/pyside6_patcher.py
[PySide6 deprecated](https://doc.qt.io/qt-6/widgets-changes-qt6.html#qdesktopwidget-and-qapplication-desktop) QDesktopWidget and QApplication.desktop we worked on #898.
SGD is not able to start after the authentication step when the window has been pinned to the status bar
This saves an internal registry (`com.shotgun-software.tk-desktop dialog_pinned` on Macos or `HKEY_CURRENT_USER\Software\ShotgunSoftware\tk-desktop\dialog_pinned` on Windows).
Changed from a lambda to a named function inside an specific patcher `_patch_QApplication` that accepts dynamic arguments. This seemed to change on runtime for PySide6 although I couldn't find any documentation about it.
Based on tests, the patched function `availableGeometry` cannot only receive a `QWidget` or `int` argument, [it can also …
> SG-37296 Add support to PySide6 for availableGeometry

- python/tank/util/metrics.py
- tests/util_tests/test_metrics.py
Events like the one defined in [breakdown2](https://github.com/shotgunsoftware/tk-multi-breakdown2/blob/c68ef176e59addb10d705b1d1ab937ca8f31020f/app.py#L119) are synced in the `EventMetric` class.
A PR in SG was made to fully support these names.
> SG-31084 Sync Unknown Events

- docs/environment_variables.rst
- python/tank/authentication/app_session_launcher.py
Python API can use a custom CA Cert store using the `SHOTGUN_API_CACERTS` variable
https://developers.shotgridsoftware.com/python-api/reference.html#shotgun-api-cacerts
App Session Launcher uses a different API and was using a different CA Cert store. It is now aligned with python-api (certifi).
Related to shotgunsoftware/python-api#373
> SG-38301 App Session Launcher to use `SHOTGUN_API_CACERTS` just like python-api

- tests/platform_tests/test_engine.py
The `test_exec_in_main_thread` is very flaky. Especially on Python 3.11/Linux
```
tests/platform_tests/test_engine.py::TestExecuteInMainThread::test_exec_in_main_thread Fatal Python error: Segmentation fault
```
**Important**: this is a temporary workaround to make CI happy while we deal with this issue.
> SG-38851 Skip the test_exec_in_main_thread test in Python 3.11 Linux

- python/tank/util/metrics.py
SG-38210 Add RV Live Review metrics
This commit adds RV Live Review events to the allowlist in metrics.py
**Context:**
Note that prior to the RV 2024 release which was based off OpenRV as a submodule, RV had its own Amplitude secret to report Amplitude events. Since that we did not want to make this secret public when we open sourced RV, this secret was removed and we lost the capability of reporting Amplitude analytics events in RV.
That being said, the RV Code was only reporting Live Review related events. 
This commit restores this functionality in RV.
This is just a proposal, please feel free to refuse this PR or ask me to rework it.
Thanks
> SG-38210 Add RV Live Review metrics

- python/tank/authentication/login_dialog.py
- python/tank/util/qt_importer.py
Web Login for PySide2/Qt5 was broken since #1012 because we wrongly imported the `QtWebEngineWidgets` module from `PySide2.QtWebEngineWidgets`.
Also fixed the UI issue `'NoneType' object has no attribute 'login_attempt'` due to wrong capabilities management of Web login.
> SG-38945 web login not working pyside2

- tests/commands_tests/test_project_wizard.py
This pull request modifies a test in `tests/commands_tests/test_project_wizard.py` to improve the validation of default configuration locations. Instead of asserting equality with static values, the test now dynamically checks that the `short_test_name` is included in the configuration locations.
This is now caused because https://github.com/shotgunsoftware/python-api/pull/217 was merged ([here](https://github.com/shotgunsoftware/python-api/pull/376)). The case-insensitive lookup was preventing loading a pipeline configuration on CI. Now it's loaded and the unit test is updated.
> Fix `test_default_configuration_location_without_suggestions`

- python/tank/util/__init__.py
- python/tank/util/metrics_cache.py
This PR restores the `from . import json` statement in `python/tank/util/__init__.py`.
Although the import does not seem to be used directly, its removal caused issues with the browser integration layer. Adding it back resolves the problem.
This regression was introduced by #1030
> SG-38307 Re-add `from . import json` in util/__init__.py to fix browser integration errors

- setup.py
Because of the change in the release process, the code used to fetch the version from Github was not working anymore.
With the code change, we're looking at all the git tags and not only the annotated tags to get the latest tag and get the version from it. 
Adding a glob match pattern as well to make sure we're not going to fetch the "non-released" tags
> [SG-40146] FIx an issue where the package version was wrong when installing using a package manager

- python/tank/util/version.py
We're logging an excessive amount of cases when the launchapp component starts to register the scanned software.
We need to plan some work in the future to fix this at the engine level on SG-40480.
Introduced by #1045
> SG-36372 Remove excessive logging

- python/tank/commands/setup_project_wizard.py
- python/tank/template.py
- tests/commands_tests/test_project_wizard.py
This PR fixes a regression introduced by #1037 where _Advanced Project Setup Wizard_ (fw-adminui) does not show the Linux path anymore.
In parallel, shotgunsoftware/tk-framework-adminui#53 fixes the other side of the retro-compatibility issue: New adminui with current core version.
> SG-40476 Restore linux2 for Advanced Project Setup wizard
