shotgunsoftware/tk-core

python/tank/platform/engine.py

Noticed while experimenting and thought I'd fix it real quick.

[minor] Fix typo in config file error message

---

python/tank/deploy/tank_commands/push_pc.py

In a localized config, there are files (`interpreter_*.cfg` and `shotgun.yml`) related to the core API that need to exist for the config to function. These files were not being copied over to the target config which caused the target config to raise the error: 
```
The Toolkit configuration path points to an invalid configuration.
```
This change will copy the necessary files only when both the source and target pipeline configurations are localized.
When the source is localized and the target is not localized, we don't copy these files. We do issue a warning saying that the files will not be copied over and provide a list of the files in question.
In summary, when running `push_configuration`:
* source config localized, target config localized ==> copy core api files
* source config …

for #28796: copy core api files during push_configuration if appropriate

---

python/tank/bootstrap/import_handler.py

The previous core swapping implementation simply removed all previous sgtk modules from `sys.modules`. This would mean that all weak references going back to the modules kept in `sys.modules` would be lost - including when classes had subclasses a component and some of the global state that was floating around.
This fix makes the behaviour a lot less brutal - instead of GCing the old module objects, they are moved in `sys.modules` (a guid prefix is attached) to keep the previous module objects in memory. For old code where the binding has already happened, everything will remain the same - for new code that is about to be executed, the new version of core will be used. 
This has the consequence that any internal bindings within sgtk will be switched round, but any external bindings will …

#36597 Less destructive core swapping

---

python/tank/api.py

Added some additional docs to explain the case where abstract paths are returned despite no files existing on disk.

 #37060 Added additional docs to abstract_paths_from_template

---

docs/platform.rst

#36962 fixed typo in documentation

---

python/tank/descriptor/io_descriptor/appstore.py
python/tank/descriptor/io_descriptor/base.py
python/tank/descriptor/io_descriptor/git_tag.py
python/tank/descriptor/io_descriptor/manual.py

Removes unnecessary warnings and clears up the logic a bit.

#37544 [minor] Remove unecessary warnings

---

python/tank/commands/core_localize.py

Fixes an issue with localization when a 0.18 core is running in desktop and is used to run the project setup for a project which is using a 0.17 core.
If you go through the setup wizard in desktop and pick an old 0.17 project, the project is copied across and the localize is trying to be smart about enumerating the descriptors and only copy bundles that are being used across to the new project. However, this bundle copying logic is based on the new 0.18 bundle disk structure, meaning that as soon as the new project starts up with its 0.17 core, it will not find the localized bundles becuase they reside in a location which is unknown to the 0.17.
This fix effectively implements the approach first done (and CRed) in #306. If a 0.17 based project is detected, the brute force copy kicks in. …

#37633 Localizes apps correctly for 0.17 cores

---

docs/platform.rst

Sphinx docs explaining engine events added.

#37636: Adds sphinx docs for engine events.

---

python/tank/util/yaml_cache.py

File was not ever closed when there was an error.

Exception safety fix in yaml cache

---

python/tank/platform/application.py
python/tank/platform/engine.py
python/tank/platform/events/event_file_close.py
python/tank/platform/events/event_file_open.py

Added `EventFileClose` class and related hooks. This matches the existing `EventFileOpen` to allow users to   respond to file close as well.
Dynamite Jira:
https://jira.autodesk.com/browse/GAME-17407

Add FileCloseEvent to engine and app.

---

python/tank/bootstrap/manager.py

This addressed behavioural tweaks in the caching policy that we discussed. I needed to add debug logging here to troubleshoot an issue so i did a quick pass on the rest since we had just discussed it.
- Sparse cache downloads items for the current engine and does not take context into account
- Added more debug messages
- Tweaked progress messages based on CR feedback
- Removed post install which was unused
- Removed unused method

[minor] Tweaks to caching policy

---

developer/build_plugin.py

- removed the buildable option - now things are always buildable
- removed the backups - instead the target folder is deleted. If a backup is desired, it's trivial to write a wrapper script to handle this

#38958 tweaks to build script

---

python/tank/util/shotgun.py
tests/util_tests/test_shotgun.py

* Catch exceptions in `register_publish` and append the created entity (if any) to the exception args.
* Updated docstring to explain how it could be used.
* Added unit tests for register_publish failures.

For #41081, report created Entity id on register_publish errors.

---

python/tank/descriptor/io_descriptor/shotgun_entity.py
tests/descriptor_tests/test_descriptors.py

Fixes a bug causing string representations of shotgun descriptors to fail.

#41423 Parsing bug for shotgun descriptors and string uris

---

python/tank/authentication/shotgun_authenticator.py

Updated docstring for create_script_user to match method parameters.

[minor] modified documentation

---

_core_upgrader.py

Concern here is changing 5 year old code that seems pretty stable. Curious
if there are pieces of the original implementation that are required for this
to account for scenarios I'm not aware of.

 #40004 Switches core update from copy/remove to move.

---

python/tank/bootstrap/cached_configuration.py
python/tank/bootstrap/manager.py
python/tank/bootstrap/resolver.py
tests/bootstrap_tests/test_manager.py

Allows for the following:
* Easy access to the resolved pipeline config’s descriptor.
* Sorting/filtering of pre-queried PipelineConfiguration entities.

#40758: Tweaks to the bootstrap API.

---

python/tank/bootstrap/resolver.py

[minor] Fixed issue with bootstrap sessions having no plugin id.

---

python/tank/util/shotgun/publish_resolve.py

Info in this section was migrated to the Admin Guide. Added a link to the Admin Guide so people can easily access the content.

Link to Admin Guide

---

python/tank/platform/engine.py

Improved the register publish docs:

#41215 improved docs

---

.flake8
.hound.yml

- Adds basic CI based linting via https://houndci.com
- Adds `.flake8` config file to core.

[minor] Added Hound integration

---

python/tank/descriptor/descriptor_config.py
scripts/tank_cmd.sh
scripts/tank_cmd_login.sh

Manage the case when Python interpreter is not a file existing on disk but a bash command.

Enable the use of a bash command for python interpreter

---

python/tank/authentication/console_authentication.py
python/tank/authentication/interactive_authentication.py
python/tank/authentication/login_dialog.py
python/tank/authentication/shotgun_authenticator.py
python/tank/authentication/user.py
tests/authentication_tests/test_interactive_authentication.py

Should you want to have a quick look @manneohrstrom , this is mainly for cleanup purposes.

Fixing use of import statements within method/functions

---

docs/utils.rst
python/tank/context.py
python/tank/descriptor/io_descriptor/shotgun_entity.py
python/tank/folder/folder_types/entity.py
python/tank/util/__init__.py
python/tank/util/shotgun_entity.py
tests/core_tests/test_context.py
tests/util_tests/test_shotgun.py

Quickly added get_sg_entity_name_field helper.
Leverage it in the place where similar code was.

Helper to deal with Entity name field.

---

python/tank/authentication/__init__.py
python/tank/authentication/shotgun_shared/saml2_sso.py
tests/authentication_tests/test_interactive_authentication.py
tests/authentication_tests/test_shotgun_authenticator.py
tests/authentication_tests/test_user.py

Added new tests prior to submitting a pull request to master.

For #45519: added new tests before refactoring of authenticate

---

developer/build_plugin.py

When baking a config ensure the target folder name includes the config name and version.
Removed some params in `_bake_configuration` which were not needed.
With `python build_plugin.py --bake ../../engines/tk-desktop2/plugins/basic /tmp/tk-desktop2`, the following structure will be build:

For #46250, stricter baked workflow.

---

developer/utils/caching.py

Skipping path descriptors as they might be using tokens that can only he evaluated at runtime.

Addendum for #46721, token for config folder

---

.travis.yml
appveyor.yml
tests/authentication_tests/test_interactive_authentication.py
tests/python/tank_test/tank_test_base.py
tests/run_travis.sh

CI now uses PySide. It would be interesting to see if we could also get PySide2 in there and rerun the test suite this way.

Adding PySide to CI

---

scripts/tank_cmd.py

When unregistering folders by entity type and id, if the entity has been retired, the error message doesn't give any indication of how to work around the problem, even though there's an easy way to do so.
Unfortunately, the problem arises before we get to the unregister_folders command itself, so the fix here is less than ideal.
**Old error:**
```
ERROR: Shot 1177 is not associated with a project and can therefore not be associated with a pipeline configuration.
```
**New error:**
```
ERROR: Shot 1177 is not associated with a project and can therefore not be associated with a pipeline configuration. If you want to unregister folders associated with this entity, you can do so by calling the unregister_folders command on the associated path instead: "tank unregister_folders /path/to/folder" …
```

For #46618: A fix for an unregister_folders error that's difficult to love.

---

developer/build_plugin.py

Optimizations for baked configs:
- If no core is specified for bootstrapping and a core is specified by the config, re-use it instead of getting latest core.
- For baked config, use the installed core to avoid core swapping on bootstrap.

For #46669, re-use associated core.

---

scripts/tank_cmd.py

We should have done this a long time ago. This has been bothering me and I hit the breaking point.

#47102 Sort commands by name when listing them

---

docs/descriptor.rst
docs/initializing.rst

Minor doc changes now that `uploaded_config` will be a default field.

SG-7322 - Update docs now that uploaded_config is a default field

---

docs/initializing.rst
docs/platform.rst
python/tank/util/shotgun_path.py

Fixes remaining warnings from our sphinx build.

For SG-8480, fix doc warnings

---

python/tank/authentication/sso_saml2/core/sso_saml2_core.py

Handle any links that asks for a new frame/window by farming out the task to the default native OS browser.

For SG-9864: handle web links and clicks in the Qt web browser

---

python/tank/authentication/shotgun_authenticator.py

Unless I'm missing something obvious, this should be `sa` not `sg`. :)

Tweak to authenticator docstring

---

docs/utils.rst
tests/run_tests.sh

Small fixes to the documentation and the run_tests.sh script used by other repos.

---

python/tank/__init__.py

This fixes an error like this one:
```
raise TypeError('{!r} is a built-in module'.format(object))
TypeError: <module 'tank_vendor.shotgun_api3.lib.six.moves.urllib' (built-in)> is a
built-in module
```
As far as the `inspect` module is concerned, builtin modules are modules that do not have `__file__`. `sys` is a good example, as it exists only in memory and is not stored somewhere on disk, unlike `os` or `pickle`. Therefore, expecting to be able to call `inspect.getsourcefile` is prone to failure. Oddly, this happens when trying to unload `tank_vendor.shotgun_api3.lib.six.moves.urllib`, which is not a builtin module *usually*, in certain setups. By this I mean that if you go and import the shotgun API in your favourite Python interpreter, the module …

Fixes a problem an import time with builtin modules.

---

python/tank/util/metrics.py

Allow events from tk-multi-reviewsubmission to reach Shotgun.

SG-16385 - Add instrumentation to track media submissions

---

software_credits
tests/python/third_party/frozen_requirements.txt
tests/python/third_party/six.py

- Upgraded six. 
- Added missing credits to software_credits. 
- Added frozen_requirements file.

SG-19789 Software Credits Update

---

docs/descriptor.rst
docs/environment_variables.rst
docs/index.rst
docs/initializing.rst

Refactoring documentation to put tk-core's environment variables in his own documentation page.

For SG-24067: Environment Variables documentation

---

scripts/tank_cmd.py

escape function moved from cgi to html.

Support python 3.9.7

---

docs/initializing.rst
info.yml
python/tank/descriptor/descriptor.py
python/tank/util/shotgun/publish_creation.py
python/tank/util/shotgun/publish_resolve.py
tests/core_tests/test_api.py
tests/platform_tests/test_application.py
tests/platform_tests/test_engine.py

This PR replaces ZD urls to AKN and developer urls

SG-21170 [ZD to AKN] Update links referenced from code to the old support site to point to AKN

---

README.md
_core_upgrader.py
docs/platform.rst
python/tank/commands/core_upgrade.py
python/tank/commands/install.py
python/tank/commands/setup_project.py
python/tank/constants.py
python/tank/descriptor/descriptor.py
scripts/tank_cmd.py

This PR replaces ZD urls to AKN and developer urls

SG-21170-ROUND2 [ZD to AKN] Update links referenced from code to the old support site to point to AKN

---

docs/platform.rst
python/tank_vendor/shotgun_api3/shotgun.py

This PR replaces ZD urls to AKN and developer urls

SG-21170-ROUND3 [ZD to AKN] Update links referenced from code to the old support site to point to AKN

---

python/tank/authentication/user_impl.py
python/tank/platform/qt/tankqdialog.py
python/tank/util/filesystem.py
python/tank/util/pickle.py
tests/authentication_tests/test_user.py
tests/core_tests/test_context.py
tests/util_tests/test_unicode.py

Catch UnicodeError exception when ensuring strings and test with an ISO-8859-1 encoding

SG-6588 SG Desktop Unicode issues

---

python/tank/authentication/user_impl.py
tests/authentication_tests/test_user.py

Catch ConnectionRefusedError exception when checking ShotGrid connectivity

SG-32890  Prevent Crash when ShotGrid Desktop starts

---

docs/core.rst
docs/descriptor.rst

- Remove duplicate elements that cause issues when rendering docs with newer versions of Sphinx
- Detected by https://github.com/shotgunsoftware/tk-toolchain/pull/52

SG-30910 Support latest version of Sphinx

---

python/tank/authentication/login_dialog.py
tests/authentication_tests/test_interactive_authentication.py

Fixup instabilities introduced by #932. Adding proper test cases.

SG-33703 authentication selection instabilities

---

python/tank/authentication/site_info.py
tests/authentication_tests/test_interactive_authentication.py

SG-33775 Remove support of legacy feature flag

---

python/tank/authentication/sso_saml2/core/sso_saml2_core.py
python/tank/authentication/user.py

- Fix a typo
- Fix wrong Qt signature. Only happen if trigger developer mode

SG-27568 Minor fixups

---

docs/environment_variables.rst

Applying a change proposed by our dear Experience Design Professional

Follow up documentation update on SGTK_ALLOW_NO_HTTPS

---

python/tank/authentication/login_dialog.py
tests/authentication_tests/test_interactive_authentication.py

SG-34230 Display all 3 auth options when available

---

python/tank/authentication/app_session_launcher.py
python/tank/authentication/login_dialog.py

Various small improvements made during the debug of SG-34358.

SG-34358 more logs and helpers

---

python/tank/authentication/sso_saml2/core/sso_saml2_core.py
tests/authentication_tests/test_interactive_authentication.py
tests/python/tank_test/tank_test_base.py

Simply use `sanitize_http_proxy` introduced in #894 and a bunch of unit tests required for coverage

SG-30117 Sanitize TK_SHOTGRID_SSO_DOMAIN

---

docs/descriptor.rst

Based on a recent support case, we need to update this documentation note.

Update documentation note

---

python/tank/util/metrics.py
tests/util_tests/test_metrics.py

Move Startup version into `Event Data` dictionary to add additional information. More info in the ticket.

SG-36057 Differenciate SGD and startup versions in metrics
